### ISSUE TITLE
set_rgb_color not setting correct values

### ISSUE THREAD

**Issue by morberg** [ggravlingen/pytradfri#102]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Stand-alone in docker dev environment.
### Version of pytradfri
4.0.2 or dev?

When setting an RGB value to a color bulb (in my case this is `lights[1]`) with the command:
`api(lights[1].light_control.set_rgb_color(142,116,51))`
the resulting RGB value when reading from the light will be:
`rgb_color: 153,109,39`

**Comment by ggravlingen** [comment]
@matemaciek may I ask you to please have a look at this?

**Comment by ggravlingen** [comment]
I had a look and it seems the gateway is providing more info after the update. I'm giving it a go to simplify color handling. Any input is appreciated!
https://github.com/ggravlingen/pytradfri/pull/103

**Comment by ggravlingen** [comment]
@morberg My current findings are that the gateway returns XY, some pre-defined hex values, color temp (for white space bulbs) and possibly hue and saturation. Thus, inputting RGB values will require a approximate transformation to either of these color representations. Need to investigate further.

**Comment by morberg** [comment]
Thanks for the update. To give some context, I'm writing an AppDaemon application that reads out the state of a light, temporarily changes it and then restores the light to its original state.

AppDaemon reports the current state of a bulb as RBG, which is why I'm using that when writing back the original state.

**Comment by Phontana** [comment]
I'm having the same issue, but not in combination with AppDaemon. When setting RGB color or color temperature from the Home Assistant front-end, it sets very low RGB values (checked on the entities page) and the icon turns black because of these low values. When setting the color through the IKEA app, everything works fine and RGB is reported back to Home Assistant with the correct values.

**Comment by ggravlingen** [comment]
@morberg and @Phontana We've decided to drop support for color conversion as conversion to XY is something that other people are able to do much better than ourselves. Instead, we will provide an example using an external lib from pypi:
https://github.com/ggravlingen/pytradfri/blob/602e8ea25e09ac20357b78c189b1d5c501e64dc5/example_color.py
