### ISSUE TITLE
cleanup on asyncio.CancelledError

### ISSUE THREAD

**Issue by NovapaX** [ggravlingen/pytradfri#110]
I'm putting some api calls in a async_timeout, because aiocoap has a 1+ minute timeout by default.

But pytradfri doesn't cleanup on a asyncio.CancelledError. 
I think it should.

The place to add such thing would be here right?
https://github.com/ggravlingen/pytradfri/blob/b4a0ee2210d6a5643bffc40829e6f093a1dbc796/pytradfri/api/aiocoap_api.py#L99-L102

```
        except asyncio.CancelledError as e:
            yield from self._reset_protocol(e)
            raise e
```

If so I would be glad to make a pull request.

**Comment by lwis** [comment]
That's fine, async_timeout would be handy as the Gateway should respond in less than a minute.

**Comment by NovapaX** [comment]
Putting things in a async_timout can also be used as a workaround for some aiocoap issues.
(for example not properly cancelling the exchange on a fatal DTLS error. Instead is lets the exchange timeout while outputting a lot of error messages.)
