### ISSUE TITLE
Check for gateway version

### ISSUE THREAD

**Issue by chrysn** [ggravlingen/pytradfri#112]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)

Stand-alone in a network that won't let the gateway access the Internet

### Version of pytradfri

4.0.5

### Expected behaviour

`python3 example_async.py GW-A0CC2BF5AC6D.amsuess.com DevicePrintedKey` should show something meaningful

### Actual behaviour

```
Traceback (most recent call last):
  File "example_async.py", line 115, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "example_async.py", line 45, in run
    psk = yield from api_factory.generate_psk(sys.argv[2])
  File "/tmp/pytradfri/pytradfri/api/aiocoap_api.py", line 198, in generate_psk
    self._psk = yield from self.request(command)
  File "/tmp/pytradfri/pytradfri/api/aiocoap_api.py", line 154, in request
    result = yield from self._execute(api_commands)
  File "/tmp/pytradfri/pytradfri/api/aiocoap_api.py", line 146, in _execute
    api_command.result = _process_output(res, parse_json)
  File "/tmp/pytradfri/pytradfri/command.py", line 71, in result
    self._result = self._process_result(value)
  File "/tmp/pytradfri/pytradfri/gateway.py", line 28, in process_result
    return result[ATTR_PSK]
TypeError: 'NoneType' object is not subscriptable
```

---

I suppose this is because I haven't let the gateway update itself since I bought it. The code it fails in indicates that the issue is with creating a per-client key and that's not supported.

To help adding a gate before trying to add an own key (and if it's only "Sorry, too old, please upgrade your GW" instead of an exception), here's my gateway's key data:

`.well-known/core`:

```
<//15001>;ct=0;obs,<//15001/reset>;ct=0,<//status>;ct=0;obs,<//15005>;ct=0;obs,<//15004>;ct=0;obs,<//15004/add>;ct=0,<//15004/remove>;ct=0,<//15006>;ct=0;obs,<//15011/15012>;ct=0;obs,<//15011/9034>;ct=0,<//15011/9030>;ct=0,<//15011/9031>;ct=0,<//15011/9063>;ct=0,<//15011/9033>;ct=0,<//15010>;ct=0;obs
```

`/15011/15012':

```
{"9029":"1.0.0008","9061":0,"9060":"1970-01-01T01:27:03.017176Z","9023":"0.debian.pool.ntp.org","9059":5223,"9062":0,"9054":0,"9055":0,"9066":0,"9069":0,"9071":0}
```

After letting the device upgrade, things ran through as expected (to the point where `lights[0]` fails because I haven't assigned any lights yet).

**Comment by schliflo** [comment]
You could just stick with 3.0.4, which was the release before the authentication update. But I agree that this issue needs to be addressed. Maybe we could add some sort of compatibility table in the readme to point users to the correct releases?

**Comment by chrysn** [comment]
I'd suggest something along the lines of `if version < 1.2.0: raise UnsupportedVersion("Gateway versions before 1.2.0 are not supported any more since pytradfri 3.0.5")`.

**Comment by jareware** [comment]
Had the same problem, this issue pointed me in the right direction. 👍

**Comment by ggravlingen** [comment]
I'll close this issue. Please feel free to raise a PR if you want some sort of gateway version check.
