### ISSUE TITLE
Support pairing

### ISSUE THREAD

**Issue by chrysn** [ggravlingen/pytradfri#113]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)

(Used stand-alone, version 4.0.5): I found no way to initiate pairing.

The handbook says that to pair a lamp/switch with the gateway I should run the app, but lacking a device where I can easily run the app, I can't even do that once to listen to how the app puts the device in pairing mode.

Do you have any clues yet as to how pairing is initiated? It should be possible to determine that from sniffing on the network.

**Comment by Lakitna** [comment]
As far I've observed from using the app for pairing here is how it happens:

1. A flag is set on the Gateway to expect a new device. This flag might be device type specific.
2. The new device is identified using lightlink. This requires the device to be close to either the Gateway, a remote, a dimmer or a motion sensor.

In this regard, it should not be very difficult to implement it. But, to be honest, I'm not sure its worth the effort. I feel like nowadays almost everyone has some sort of smartphone or tablet on which they can run the official app to manage the devices in the network.

**Comment by ggravlingen** [comment]
I found a constant called commissioning mode, which is available in my unmerged PR: https://github.com/ggravlingen/pytradfri/blob/5c8e2c79d0acddfe51fac28b147c921c2a325dc2/pytradfri/const.py#L17

Could setting this to something be what the app does?

**Comment by Lakitna** [comment]
Yes, that could be the flag. Only one way to find out :)

But due to the comprehensive wizard-like pairing screens in the app, it's a bit obscure how many flags there are for all the different combinations and devices. Maybe there is just one, but there could be one for every device category (input or output) or even for every device type (remote, dimmer, motion sensor, light bulb, light panel, light door, spotlight etc.). Though the last one is unlikely.

**Comment by chrysn** [comment]
> I feel like nowadays almost everyone has some sort of smartphone or
> tablet on which they can run the official app to manage the devices in
> the network.

Not if they're working in an environment where they don't want to or
must not employ nonfree software, or want to automate the process
further.

On Wed, Nov 15, 2017 at 11:54:08AM +0000, Sander van Beek wrote:
> Yes, that could be the flag. Only one way to find out :)

will do once back home.

**Comment by Lakitna** [comment]
> Not if they're working in an environment where they don't want to or must not employ nonfree software, or want to automate the process further.

While I can't think of a situation where non-free software would be an issue, the automation thing is a good point.

**Comment by chrysn** [comment]
Hm, a PUT to `coaps://GW-A0CC2BF5AC6D.amsuess.com/15011/15012` with payload `{"9061":1}` does lead to the radio-link LED blinking, but I didn't get it to pair (either by having the switch, with button pressed or not pressed, or the LED nearby).

Installing the app and sniffing on the network revealed that I got the payload wrong: 180 is the number, and the number is 180 -- no matter whether adding a motion sensor, a remote control or a wireless dimmer.

I'm trying now whether that is sufficient to get working pairings from a factory reset.

**Comment by chrysn** [comment]
Given the "180" value counts down in GETs, it's probably a timeout. It seems to reset to 0 when something is paired.

A few seconds after that, a new group spawns (which the app immediately names), and a few seconds later a device spawns (which the app also immediately names). That being done, the app disables pairing (even though the device's reset of the value indicates to me that it already was).

I've tested that, from a factory reset state of a bulb, a switch and the gw, it is sufficient to
* set the 9061 timeout
* press the switch's pairing button for 10s near the gw
* turn on the light bulb
* press the button again to pair with the light bulb

Then, example_async.py can act on the lamp.

As a next step, I'd put that into an `example_pair.py` script along with some checks; could such a script (or whatever comes of it) live in pytradfri?

**Comment by lwis** [comment]
Absolutely! I'm thinking we may need an examples directory 😄

**Comment by ggravlingen** [comment]
@lwis agree on moving examples to a separate dir. Made an attempt this weekend but got stuck on doing the imports of pytradfri from a subdirectory. Does the example dir need an __init__.py to work properly?

**Comment by chrysn** [comment]
If it helps, in aiocoap I distinguish three kinds of programs:
1. tools (eg. `aiocoap-client`) – general-purpose, (mostly) production quality tools that ship with the library
2. examples (eg. `clientGET.py`) – scripts residing in the library's root directory. Their target is to be an easy first contact point for developers that learn by example, and not to be generally useful in any way
3. contrib scripts (eg. `aiocoap-fileserver`) – tools that are too small to be their own project, too complex to serve as an introductory example, and too valuable to the author or power users to just sit around in `~/bin`, but not polished enough to be convenient for casual users

The way I wrote the script, it would probably be most suitable for the third category. aiocoap is having module `__init__.py` files only for the first category, as those are actual python modules that are exposed to setup.py as `entry_points` and thus installed into `/usr/bin` when pip-installing.

**Comment by chrysn** [comment]
On Wed, Nov 15, 2017 at 11:54:08AM +0000, Sander van Beek wrote:
> Maybe there is just one, but there could be one for every device
> category (input or output) or even [...]

My experience has been that pairing of outputs is not at all driven by
the app; it only serves as an electronic manual and guide there and
presents visual confirmation of the pairing once the device arrives, but
has no active role in it.

**Comment by sixtyfive** [comment]
It seems the `example_pair.py` script was removed again at some point. Was it not working anymore?

**Comment by ggravlingen** [comment]
You should be able to find it in the history:
https://github.com/home-assistant-libs/pytradfri/commits/master/examples

**Comment by chrysn** [comment]
My latest version was merged in https://github.com/home-assistant-libs/pytradfri/pull/114 -- you can copy it out from "files changed" and at <https://github.com/chrysn-pull-requests/pytradfri/blob/601d161980fb106723ea1f8621e8710acdb84017/example_pair.py>.

Haven't run it for ages, though...

**Comment by sixtyfive** [comment]
Yes, I had gotten it from the history. Unfortunately it doesn't work, throwing the error I posted above. Oh well, time to find a phone that can run the IKEA app, then. Thank you both!
