### ISSUE TITLE
Has anyone tried observing the tradfri motion montior with pytradfri

### ISSUE THREAD

**Issue by balu-** [ggravlingen/pytradfri#115]
not a real Issue, more a question:
I was asking myself if i could use the IKEA tradri series (gateway & motion dector) with pytradfri to detect motion and run linux commands if motion is detected.
I'm not sure if this is possible but i thought maybe somebody has or can try it.

**Comment by lwis** [comment]
Unfortunately it didn't (haven't checked the latest firmware) return any motion events when observed.

**Comment by balu-** [comment]
@lwis thank you, you saved me some mony and disapointment 👍

**Comment by ggravlingen** [comment]
Tried with the most recent firmware and it doesn't work. 😟
