### ISSUE TITLE
Color temperature in 5.0.0

### ISSUE THREAD

**Issue by Lakitna** [ggravlingen/pytradfri#119]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Stand-alone

### Version of pytradfri
5.0.0

### Expected behaviour
Return color temperature in Kelvin (though Mireds would work too)

### Actual behaviour
Return `None`

My program depends on using color temperatures to define the color of the lamps. I was just trying to port my program to 5.0.0 when I found out that I can't directly get the color temperature anymore as the function returns `None`.

I traced it to the following code in `device.py`

    @property
    def color_temp(self):
        if self.supported_features & SUPPORT_COLOR_TEMP:
            if self.raw.get(ATTR_LIGHT_MIREDS) != 0:
                return self.raw.get(ATTR_LIGHT_MIREDS)

I'm calling the function like this:

    light = device.light_control.lights[0]
    print(light.dimmer) # returns proper dimmer value
    print(light.state) # returns proper state value
    print(light.color_temp) # returns None

**Comment by Lakitna** [comment]
I've been investigating a bit by monitoring the raw output. Look for key `5711`.

In the previous pytradfri it was no problem to set the lamps to a not predefined value. In my program I'm using the full range from 2200 to 4000 Kelvin with every value in between to make smooth transitions.

When the color temperature value is not a predefined one, like those you set with the remote or app, it returns `0` Mired. Because of the check below it returns `None` instead of `0`

    if self.raw.get(ATTR_LIGHT_MIREDS) != 0:

**Comment by ggravlingen** [comment]
@Lakitna can you please provide `print(light.raw)`, preferrably using pprint instead of print. I think this is related to what values the gateway actually accepts. 5.0.0 did contain a few breaking changes in terms of color and temp conversion in the lib.

**Comment by Lakitna** [comment]
Of course. Here is one of my white spectrum bulbs:

    {   '5706': '0',
        '5709': 24938,
        '5710': 24689,
        '5711': 0,
        '5850': 1,
        '5851': 254,
        '9003': 0}

The values of the bulb at the moment of request are `{'brightness': 254, 'color': 4000, 'state': True}`

**Comment by ggravlingen** [comment]
So you are doing light_control.set_temp(xx) and you cannot set whatever color_temp you want?

**Comment by Lakitna** [comment]
Hmm behavior has changed. After switching out the old Kelvin scale for the new Mired scale it seems to work as it should. Apparently, I didn't change everything properly when I made the issue.

Maybe some feedback is in order if someone tries to use a non-mired value?

**Comment by ggravlingen** [comment]
OK, sounds good that it works as expected now! :+1:  Uncertain about checking for non-mired value though. :thinking:
