### ISSUE TITLE
How to get a serial number/unique identifier of a bulb?

### ISSUE THREAD

**Issue by jtulak** [ggravlingen/pytradfri#122]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
standalone
### Version of pytradfri
Tried 5.0.0 and 5.2.0 
### Expected behaviour
Finding a serial number or another unique identifier at `device.device_info.serial`.
### Actual behaviour
The `serial` field is empty. The `raw` field contains: `{'0': 'IKEA of Sweden', '1': 'TRADFRI bulb E27 CWS opal 600lm', '2': '', '3': '1.3.002', '6': 1}` and according to the definition of `DeviceInfo`: `ATTR_SERIAL = '2'`, which is indeed empty.

The gateway changes the order of bulbs on every reboot, so I can't rely on the order in which pytradfri reports them. I found issue #99, but that was closed by the OP without any resolution, and it seems that he was asking for a different API, but knew how to get an ID.

Is the serial number located somewhere else, or is it an issue with either pytradfri or the gateway itself?

**Comment by ggravlingen** [comment]
Hi @jtulak,

The purpose of this library is to represent the way the gateway works. We're not trying to add any functionality, so if there is nothing in the raw string, the gateway does not report it. Hence, if you want to keep the order of the bulbs over each reboot, this is logic that needs to be built in your implementation of pytradfri.

If you figure out a way of implementing this, I would happily include it in one of the example files as I'm sure many others look for this feature.

**Comment by jtulak** [comment]
OK, so it is an issue with the gateway itself. Unfortunately, from the information accessible through pytradfri, I see no way of identifying the bulbs. It looks like with the addition of groups into pytradfri, I should be able to work around in this case, though...

**Comment by Lakitna** [comment]
If you can name the bulbs (via the app) you can use the lamp names as unique identifiers. I am using names in my program to separate lamps.

**Comment by ggravlingen** [comment]
@Lakitna interesting! Care to show how you did it in a gist or something?

**Comment by Lakitna** [comment]
I'll give it a shot, but my program has grown complex. I'll write up a manageable version real quick. If you want to see my complex thing check [Onaeri-tradfri](https://github.com/Lakitna/Onaeri-tradfri) and [Onaeri](https://github.com/Lakitna/Onaeri).

Say: There are three lamps on the network. Using the device manager on the official Ikea app I named them `Alpha 1`, `Alpha 2` and `Beta 1`. In my use case, I want lamps with the same group name to be treated equally. In this case, the lamps `Alpha 1` and `Alpha 2` would be treated equally while `Beta 1` is treated separately.

Take the following code:

```python
# Like we know en love from the examples
lampList = [dev for dev in devices if dev.has_light_control]

# Define the different group names
groupNameList = ['Alpha', 'Beta']

# Make an empty dict to store our groups
groups = {}

# Iterate all group names
for groupName in groupNameList:
    groups[groupName] = []
    
    # Iterate all lamps on the network
    for lamp in lampList:
        # Check if the group name is a partial of the lamp name. By forcing both to be lowercase the check is case insensitive.
        if groupName.lower() in lamp.name.lower():
            groups[groupName].append(lamp)

# Output the group hierarchy
print(groups)
```

I know it's kind of gross to have two for-loops nested like this, but the amount of iterations is very low so I don't really care about performance here.

This code will output the following:

```python
{
    'Alpha': [
            <65545 - Alpha 1 (TRADFRI bulb E27 WS opal 980lm)>,
            <65537 - Alpha 2 (TRADFRI bulb E27 WS opal 980lm)>
        ],
    'Beta': [
            <65539 - Beta 1 (TRADFRI bulb E27 WS opal 980lm)>
        ]
}
```

After this point, you can use the new hierarchy in your program. For example like this:

```python
for lamp in groups['Alpha']:
    dim_command = lamp.light_control.set_dimmer(254)
    api(dim_command)
```

Please note that the order of `Alpha 1` and `Alpha 2` can change with this particular code, but that should be an easy fix.

**Comment by jtulak** [comment]
@Lakitna Thanks! I didn't realize I can access the name when I didn't see it in `device_info`. This is a pretty nice workaround that solved my issue. 👍

@ggravlingen I think this is worthy of being mentioned somewhere. Maybe it doesn't have to be in the examples, just a few words in the readme, but I imagine quite a lot people will find it useful. What do you think?

**Comment by Lakitna** [comment]
Accessing the name is actually in the examples, in both sync and async. So an additional comment should do the trick.

**Comment by jtulak** [comment]
Hmm... might be that I began to use pytradfri early on, when these examples were not there, and then didn't look into them in details. Mea culpa.

**Comment by ggravlingen** [comment]
@Lakitna thank you! I added your code to the Wiki just to have it stored somewhere: https://github.com/ggravlingen/pytradfri/wiki/Misc-code-snippets

Also ping @jtulak for suggesting to store the code snippet. :taco: :tada:

**Comment by jtulak** [comment]
@ggravlingen Ok, then I think we can close this issue. I suggest wontfix, because the name is a workaroud and until the gateway changes, there is nothing else to do...

**Comment by ggravlingen** [comment]
@jtulak OK! Thanks for raising this issue, it lead to the opening of the wiki pages. :+1:
