### ISSUE TITLE
Color ranges

### ISSUE THREAD

**Issue by Lakitna** [ggravlingen/pytradfri#132]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Stand-alone

### Version of pytradfri
5.2.0

I can't find the min and max values of some color properties. I'd like to normalise the values, so I need the absolute minimum and maximum values. Does anyone know them? If they are unkown I'll write a script to find out.

* Hue (best guess: [0, 64800])
* Saturation (best guess: [0, 65279])

Might be a good idea to add things like this to the wiki.

**Comment by ggravlingen** [comment]
To me they are unknown. I only found out this week what parameter is hue and what is saturation. Had them mixed up before. Please feel free to provide an analysis! We won't do any conversion in pytradfri though as we're trying to be an api only.

**Comment by Lakitna** [comment]
Agreed it wouldn't be a good idea to convert it in pytradfri. Instead, we should just document it.

Here are my findings. Turns out it's pretty easy to find out this stuff. Since the values are unsigned simply sending a value of `-1` results in the value rolling over and the lamp being set to the highest possible value. That value can be retrieved by observing the lamp.

**Color temperature**
Range: `(250, 454)`

**Brightness**
Range: `(1, 254)`
Power off on `0`
unsigned 8-bit integer

**Hue**
Range: `(0, 65535)`
unsigned 16-bit integer

**Saturation** 
Effective range: `(0, 65279)`
After the effective range, the lamp will just go black, even though the bulb accepts a bit more range.

Absolute range: `(0, 65535)`
unsigned 16-bit integer

**XY color**
X range: `(0, 65535)`
unsigned 16-bit integer

Y range: `(0, 65535)`
unsigned 16-bit integer

**Comment by ggravlingen** [comment]
@Lakitna great work! Perhaps we could document this among the constants?

**Comment by Lakitna** [comment]
Yes, that would be an easy and reliable way to grab it and it's pretty easy to find. I think it's a good idea to duplicate it on the wiki too, to make it easier to find for newbies.

Unlike the `MIN_MIREDS_WS` and `MAX_MIREDS_WS` that are already in const.py I would order it in a tuple. It makes more sense to me. For example: `MIREDS_WS = (250, 454)`.

**Comment by ggravlingen** [comment]
@Lakitna I created a wiki-page as per your suggestion. Do you want to submit the updated MIREDS_WS-constant as a PR?

**Comment by Lakitna** [comment]
I'll make a PR with all ranges in const.py
