### ISSUE TITLE
Setting color values individually

### ISSUE THREAD

**Issue by Lakitna** [ggravlingen/pytradfri#138]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Stand-alone

### Version of pytradfri
5.2.1

### Expected behaviour
```
lamp.light_control.set_hsb(1000, 1000, None)
```
Above code should update hue and saturation, but leave brightness unchanged. This is the behaviour of 5.2.0

### Actual behaviour
Program crashes with the following (partial) traceback:

```
  File "/usr/local/lib/python3.6/site-packages/pytradfri/device.py", line 224, in set_hsb
    self._value_validate(brightness, RANGE_BRIGHTNESS, "Brightness")
  File "/usr/local/lib/python3.6/site-packages/pytradfri/device.py", line 266, in _value_validate
    if value < rnge[0] or value > rnge[1]:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

In other words. The value validation I wrote blocks this type of use.

### Solution
The easiest solution is changing the value validation to allow `None` as a value. 

See PR #139

**Comment by ggravlingen** [comment]
This can be closed now?

**Comment by Lakitna** [comment]
Yes
