### ISSUE TITLE
unable to get a put request through coap-client DTLS (get works fine)

### ISSUE THREAD

**Issue by diplix** [ggravlingen/pytradfri#14]
i installed libcoap as instructed (as of pytradfri 1.0) and my tradfri bulbs are displayed ok (in the HA dev version) and even status changes are displayed (with a short delay). switching in HA however fails. in the HA logs a client error (4.00) appeared in pytradfri version < 1.0. now there are no more errors in the log, but switching still doesn’t work.

looking into the matter through `coap-client` shows this:

```
echo '{ "3311" : [{ "5851" : 20 }] }' | coap-client -u "Client_identity" -k "xxx" -v 10 -m put "coaps://192.168.1.68:5684/15001/65539" -f -

Apr 18 20:12:48 DEBG created DTLS endpoint 0.0.0.0:57153
v:1 t:CON c:PUT i:07c5 {} [ ]
Apr 18 20:12:48 DEBG sending CoAP request:
v:1 t:CON c:PUT i:07c5 {} [ Uri-Path:15001, Uri-Path:65539 ]
Apr 18 20:12:48 DEBG *** new session 0x7fb09ae00610
Apr 18 20:12:48 DEBG call dtls_write
Apr 18 20:12:48 DEBG *** add 0x7fb09af00130 to sendqueue of session 0x7fb09ae00610
Apr 18 20:12:48 DEBG timeout is set to 90 seconds
Apr 18 20:12:48 DEBG received 60 bytes on fd 3
Apr 18 20:12:48 DEBG received 63 bytes on fd 3
Apr 18 20:12:48 DEBG received 25 bytes on fd 3
Apr 18 20:12:48 DEBG received 14 bytes on fd 3
Apr 18 20:12:48 DEBG received 53 bytes on fd 3
Apr 18 20:12:48 DEBG *** EVENT: 0x01de
Apr 18 20:12:48 DEBG received 33 bytes on fd 3
Apr 18 20:12:48 INFO ** application data:
v:1 t:ACK c:4.00 i:07c5 {} [ ]
Apr 18 20:12:48 DEBG *** removed transaction 291
Apr 18 20:12:48 DEBG ** process incoming 4.00 response:
v:1 t:ACK c:4.00 i:07c5 {} [ ]
4.00
Apr 18 20:12:48 DEBG *** removed session 0x7fb09ae00610

```

i tested this on mac os 10.12 (sierra) and 10.11 (el capitan). seems to be an SSL problem (again) occurring only on mac os. however, @balloob, you also use a mac — and your coap-client seems to work fine. any additional SSL stuff or libs you installed?

**Comment by ws141** [comment]
I had the same issue when I compiled the coap-client in macOS Sierra. Gave eventually up and got it to work on my Raspberry Pi running linux.

**Comment by diplix** [comment]
😔

**Comment by balloob** [comment]
I develop inside docker: `zsh script/dev_docker` will build an image that is ready to go with your repo mounted inside the container so no need to restart it.

**Comment by diplix** [comment]
amazingly this works. i was wondering how to put it together with HA, until i tried installing HA dev version into docker as described [here](https://home-assistant.io/docs/installation/docker/). even more amazingly, this runs smootly and gives me tradfri light control without even installing or running the `tradfri-dev` container.

**Comment by balloob** [comment]
haha, I actually meant the tradfri_dev docker script, but yeah, the HASS dev_docker script will work too

**Comment by diplix** [comment]
found a working `coap-client` binary for macos at the homebridge tradfri project: https://github.com/jesper-lindberg/homebridge-tradfri/tree/master/bin

it’s working on macos sierra, but it seems to require the `-u "Client_identity"` bit as argument — otherwise i didn’t get it to work.

sidenote: [this project](https://github.com/hardillb/TRADFRI2MQTT) has a working implementation for observing the hub and reflects changes in tradfri light status instantaneously.
