### ISSUE TITLE
Support for Hue Motion Sensor

### ISSUE THREAD

**Issue by rmettes** [ggravlingen/pytradfri#143]
Currently there is no (trigger) support for the tradfri motion sensors. Because the device won't trigger an event when motion is detected. However the Philips Hue Motion sensors should sent such an event.

The Hue motion sensor is capable of pairing with the Tradfi hub and the stats are listed correctly in Home Assistant. Is there a way to check if the Hue motion sensor is sending an event to the Tradfri hub when motion is detected?

Also the Hue motion sensor records temperature and light level, can these variables pulled from the tradfri hub?

**Comment by lwis** [comment]
You'll have to write a script which subscribes to the events of the sensor, and see what events come out of the device. I don't have a Hue sensor, so I can't develop support for it. If you're successful, and the library requires any more changes, feel free to raise a pull request!

**Comment by rmettes** [comment]
Are there any leads how to subscribe to events of sensors / devices? I'm sure this is also used to discover the Tradfri devices.

**Comment by lwis** [comment]
Check `example_async.py` for an example.

**Comment by Lakitna** [comment]
More specifically line 98 through 111 in `example_async.py` or line 48 through 61 in `example_sync.py`

**Comment by rmettes** [comment]
Nice! I'll check this out

**Comment by rmettes** [comment]
Ok, so far I got some response from the Hue Motion tracker. But it's looking a lot like the Tradfri Motion Sensor:
{
    "3":
        {
            "0":"Philips",
            "1":"SML001",
            "2":"",
            "3":"6.1.0.18912",
            "6":3,
            "9":200
        },
    "3300":[{"9003":0}],
    "5750":4,
    "9001":"Hue Motion",               
    "9002":1516734900,
    "9003":65551,
    "9019":1,
    "9020":1516735819,
    "9054":0
}

I'm currently not in range of the motion sensor to check out if there is some kind of event when it's registering some movement. But I hoped for some more 'static' reply data about temperature and light level.

**Comment by lwis** [comment]
In my experience the Tradfri motion sensor only sends one event, then goes silent when you subscribe.

I think this is a limitation of the gateway, not of the device itself. 

The only way I've heard of checking sensor events is by using a ZigBee stick directly.

**Comment by Lakitna** [comment]
For comparison the data of a tradfri motion sensor:

```
  {
    "3": {
      "0": "IKEA of Sweden",
      "1": "TRADFRI motion sensor",
      "2": "",
      "3": "1.2.214",
      "6": 3,
      "9": 87
    },
    "3300": [
      {
        "9003": 0
      }
    ],
    "5750": 4,
    "9001": "User defined name",
    "9002": 1508581932,
    "9003": 65540,
    "9019": 1,
    "9020": 1511265271,
    "9054": 0
  }
```
Seems to be exactly the same.

**Comment by ggravlingen** [comment]
Yeah, I agree with the previous posts. There is not much that can be done until the gateway exposes the values of the motion sensor, which it doesn't do today.

**Comment by rmettes** [comment]
Checked this evening if the Hue Sensor has the same behavior as the Tradfri Sensor as lwis described. And it does.. No events registered on the hub as it seems.

Hopefully Ikea implements the exposure of the sensor data one day.

Case closed?

**Comment by lwis** [comment]
For now, sadly, yes!
