### ISSUE TITLE
[INFO] official IKEA Tradfri representative now on reddit

### ISSUE THREAD

**Issue by schliflo** [ggravlingen/pytradfri#144]
I just wanted to let you guys know that there is now an official IKEA representative on /r/tradfri: https://www.reddit.com/r/tradfri/comments/7svzk1/welcome_utradfri_an_official_representative_from/
Could come in handy when there are some specific questions etc..
@ggravlingen as this is just for information purposes, feel free to close this issue anytime ;)

**Comment by ggravlingen** [comment]
Thanks for the heads up @schliflo!

**Comment by lwis** [comment]
Thanks! I've dropped the rep a message.
