### ISSUE TITLE
Use Ikea Remote separately from Group of Bulbs / Remap Buttons

### ISSUE THREAD

**Issue by alex-savin** [ggravlingen/pytradfri#145]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant v 0.61.1

### Expected behavior
Is it possible to use Ikea Remote as a dedicated switch?! I mean to remap buttons actions on Home Assistant side.
I would prefer to use button which assigned to change temp of color, to change room scene.
I checked out that it possible to create a group and remove all of the bulbs from it and leave only remote in it
### Actual behavior
Not possible

**Comment by ggravlingen** [comment]
@alex-savin unfortunately the gateway does not return events created by the remote so it's currently not possible. This is similar to the behaviour discussed on the motion sensor here: #143

It might work if you use substitute for the IKEA gateway, such as a Conbee stick. I haven't tested it though so I can't confirm if it works.
