### ISSUE TITLE
Help writing unit tests wanted

### ISSUE THREAD

**Issue by ggravlingen** [ggravlingen/pytradfri#147]
I would like to improve the coveralls stats so if you want to contribute to this library, please feel free to add more tests to the test suite! :raised_hands:

**Comment by matemaciek** [comment]
Great direction, I'm totally for it. Sadly I cannot contribute right now as I am in process of moving to another country, but I'll try to help after that.

**Comment by Lakitna** [comment]
I agree. How about we strive for improving the coverage with every new PR by `n`%?

Sitting down and writing tests can be cumbersome, but if you're changing the code anyway it's not so much of a hassle. At least that's how it is for me.
