### ISSUE TITLE
Remotes recognised as lamps

### ISSUE THREAD

**Issue by Lakitna** [ggravlingen/pytradfri#150]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Stand-alone

### Version of pytradfri
5.3.0

### Expected behaviour
```
light_objects = [dev for dev in devices if dev.has_light_control]
```
Above code returns all lamps, but not other devices

### Actual behaviour
The code returns both lamps and remotes, but not motion sensors.

I this is probably due to the GU10 fix from #135 (PR #141). I think we should reverse this fix.

**Comment by Lakitna** [comment]
Yes. Removing line 75 in `device.py` fixes this issue.

**Comment by ggravlingen** [comment]
@Lakitna is the remote listed under `ROOT_SWITCH`?

**Comment by ggravlingen** [comment]
Can we also please rule out that this error persists after re-pairing a remote?

**Comment by Lakitna** [comment]
The remote does use `ROOT_SWITCH`. I've encountered this issue on two separate systems (my fathers and my own).

I'll pair a new remote, but expect the same thing since `ROOT_SWITCH` seems to be the default key for remotes. See https://gist.github.com/Lakitna/b6b041410431bcedff67a947640fb281

**Comment by Lakitna** [comment]
I've been able to verify that, indeed, remotes use `15009` to store their value (singular). The GU10s of #135 identified as remotes. The fix you and @lwis made, make the remotes show up with `has_light_control`.

Perhaps someone else can confirm this on their own network using `examples/debug_info.py`? Just make sure you download the latest pytradfri first (via github, not via pip).

**Comment by lwis** [comment]
I'm almost certain that IKEA have acknowledged this bug, so my vote is to revert that commit entirely. If anyone has this issue, they should factory reset their gateway as it appears to be caused by the firmware upgrade not migrating bulbs correctly.

**Comment by Lakitna** [comment]
After looking at it, I found some structural changes too. Do you want to revert them too?

**Comment by lwis** [comment]
Yup, whole commit can be reverted. Only thing we need to keep is the readme changes.
