### ISSUE TITLE
E26 WS opal 980lm bulbs need to be re-paired to be seen as lamps with device FW 1.2.217 and gateway fw 1.3.14

### ISSUE THREAD

**Issue by coolnovember** [ggravlingen/pytradfri#152]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)

pytradfri stand-alone. (to be integrated with domoticz)

### Version of pytradfri
pytradfri-5.3.1

### Expected behaviour
Bulbs need to be identified as lamps. Not generic devices

### Actual behaviour
Bulbs only show up as devices until re-paired after updating to the latest firmware and gateway software

--------------

This involves the behavior reported in https://github.com/ggravlingen/pytradfri/issues/142 and https://github.com/ggravlingen/pytradfri/issues/135

This can probably be merged to one of the below issues. I'm reporting this separately because the two issues below refer a slightly different model compared to mine.

Out of the box, paired with the app.
Installed pytradfri and I see this

```json
Printing information about all devices paired to the Gateway
[
    {
        "15009": [
            {
                "9003": 0
            }
        ],
        "3": {
            "0": "IKEA of Sweden",
            "1": "TRADFRI remote control",
            "2": "",
            "3": "1.1.1.1-5.7.2.0",
            "6": 3,
            "9": 74
        },
        "5750": 0,
        "9001": "TRADFRI remote control",
        "9002": 1519528423,
        "9003": 65536,
        "9019": 1,
        "9020": 1519575906,
        "9054": 1
    },
    {
        "15009": [
            {
                "5706": "0",
                "5709": 0,
                "5710": 0,
                "5711": 0,
                "5717": 0,
                "5850": 0,
                "5851": 0,
                "9003": 0
            }
        ],
        "3": {
            "0": "IKEA of Sweden",
            "1": "TRADFRI bulb E26 WS opal 980lm",
            "2": "",
            "3": "1.2.217",
            "6": 1
        },
        "5750": 0,
        "9001": "TRADFRI bulb E26 WS opal 980lm",
        "9002": 1519530176,
        "9003": 65537,
        "9019": 0,
        "9020": 1519534616,
        "9054": 0
    },
    {
        "3": {
            "0": "IKEA of Sweden",
            "1": "TRADFRI bulb E26 WS opal 980lm",
            "2": "",
            "3": "1.1.1.1-5.7.2.0",
            "6": 1
        },
        "5750": 1,
        "9001": "TRADFRI bulb E26 WS opal 980lm 2",
        "9002": 1519575885,
        "9003": 65538,
        "9019": 1,
        "9020": 1519575894,
        "9054": 1
    }
]
```
Notice, that one bulb has updated, but not the second one. 
But both of them show the 15009 identifier.

Then based on the experiment in https://github.com/ggravlingen/pytradfri/issues/135 , I used the app to remove each bulb. (this causes the bulb to reset) and then re-added them to the app.

After the re-add, they show up correctly.

```json
Printing information about all lamps paired to the Gateway
[
    {
        "3": {
            "0": "IKEA of Sweden",
            "1": "TRADFRI bulb E26 WS opal 980lm",
            "2": "",
            "3": "1.2.217",
            "6": 1
        },
        "3311": [
            {
                "5706": "f1e0b5",
                "5709": 30138,
                "5710": 26909,
                "5711": 370,
                "5717": 0,
                "5850": 0,
                "5851": 254,
                "9003": 0
            }
        ],
        "5750": 2,
        "9001": "TRADFRI bulb E26 WS opal 980lm 2",
        "9002": 1519576651,
        "9003": 65539,
        "9019": 1,
        "9020": 1519576660,
        "9054": 0
    },
    {
        "3": {
            "0": "IKEA of Sweden",
            "1": "TRADFRI bulb E26 WS opal 980lm",
            "2": "",
            "3": "1.2.217",
            "6": 1
        },
        "3311": [
            {
                "5706": "f1e0b5",
                "5709": 30138,
                "5710": 26909,
                "5711": 370,
                "5717": 0,
                "5850": 1,
                "5851": 254,
                "9003": 0
            }
        ],
        "5750": 2,
        "9001": "TRADFRI bulb E26 WS opal 980lm 3",
        "9002": 1519576799,
        "9003": 65540,
        "9019": 1,
        "9020": 1519576808,
        "9054": 0
    }
]
```

**Comment by coolnovember** [comment]
Also, if your E26 WS opal 980lm bulbs won't start the pairing process:
a) Make sure you do the manual 6 time on/off process. ( Important, based on a thread somewhere on the smartthings forum, you have to time it - that seemed to work for me. When you flick it on and off, the Off time needs to be larger (1 second) than ON time (0.5 second).)
b) Change the battery on your remote from the one that comes with the package. The one that came with the remote died after the first pair, and the second bulb wouldn't even start.
Note - After the 4th set of pairing, my remote is again complaining of low battery in the app. Pairing is apparently very battery intensive.

**Comment by ggravlingen** [comment]
Thanks for logging this! The behaviour is indeed the same as seen in the past. How should we treat this issue? Close it and keep it as reference?

**Comment by Lakitna** [comment]
I think that's a good idea. At least until this has been fixed by Ikea. They have been notified via the official Reddit a few months ago.

**Comment by ggravlingen** [comment]
OK, let's keep the issue as a reference. Closing it.
