### ISSUE TITLE
How to set timeout for commands?

### ISSUE THREAD

**Issue by tazle** [ggravlingen/pytradfri#154]
Currently Command objetcts returned from e.g. `Gateway.get_devices()` have their timeout set to 10 seconds. I would like to set significantly shorter timeouts for certain commands, but this does not seem to be possible with the current API short of modifying `_timeout` of the returned Command directly.

It would be good to have some way to override timeouts. Perhaps on the `request()` method of `APIFactory`?

**Comment by ggravlingen** [comment]
Hi @tazle,

We strongly encourage pull requests if you want to add a feature. We're also quite quickly on reviewing and pushing to pypi. :)

Ping @lwis for core api stuff.

**Comment by lwis** [comment]
Rather than passing the timeout in everywhere we could add a constant on https://github.com/ggravlingen/pytradfri/blob/master/pytradfri/command.py which can be set to override the default value of 10s?

**Comment by tazle** [comment]
I will write the code if we can agree on the approach.

Some approaches with pros and cons, including the ones @lwis mentioned above:

1. Add optional timeout parameter to APIFactory constructors. Setting the parameter would override timeouts of individual commands. Seems a bit heavy-handed to me, actually.
1. Add some way to configure the default timeout to Command class. Changeable class constants seems like a fine python hack, but not very good for the official way to achieve this.
1. Add **kwargs to every method that produces Commands. Propagate the values to Command constructor. Requires code changes everywhere.
1. The Java approach: add CommandFactory where the default timeout can be set. Change everything that produces a Command to use a CommandFactory instead of the class. Requires changes everywhere. User could maybe get away with passing a CommandFactory to Gateway?
1. Add TimeoutCommand Command implementation that overrides timeout and delegates everything else to some Command instance. Have user wrap the Commands they want with TimeoutCommand wrappers.

None of the approaches should beark existing user code.

**Comment by lwis** [comment]
Alternatively we expose a setter for _timeout on `Command` which allows the user to change timeouts on commands at their discretion. I believe that's where this behaviour belongs. This, however, does not solve changing the default timeout.

**Comment by tazle** [comment]
It turns out there aren't that many places where Commands are instantiated (set_values in Device, a few usages in ApiResource, plenty in gateway, set_values in StartActionItemController), so perhaps the CommandFactory approach would be reasonable?

**Comment by lwis** [comment]
I don't think factory is the correct pattern to use here, as it will always be returning a `Command`, just configured differently. Builder is maybe more appropriate.

That said, timeout is the only thing we would want to be configurable, so I'm inclined to say that it would be best to add timeout as an optional parameter to Gateway.

**Comment by tazle** [comment]
How about just removing timeout from Command completely, and moving it to APIFactory (both a default timeout and request() parameter to override it)?

**Comment by lwis** [comment]
That makes the most sense actually, timeout isn't related to the core API, it's related to the IO.

**Comment by tazle** [comment]
Ok, I'll get to it.

**Comment by tazle** [comment]
See #155.
