### ISSUE TITLE
Difference of asynchronous application and synchronous application

### ISSUE THREAD

**Issue by CoorFun** [ggravlingen/pytradfri#166]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home assistant

The instruction of installation are separated into two parts: asynchronous application and synchronous application.

Could someone can explain me what's the difference of these two kinds application?

**Comment by lwis** [comment]
asynchronous is non-blocking and uses aiocoap and asyncio, whereas synchronous is blocking.

**Comment by CoorFun** [comment]
Thanks Iwis, but could you please give an example to explain? For instance, I want to use your library with Snips voice assistant to control Ikea bulbs, which mode it belongs to?

**Comment by lwis** [comment]
There are [examples](https://github.com/ggravlingen/pytradfri/tree/master/examples) in the project.

**Comment by ggravlingen** [comment]
Could perhaps this video shed some light on the difference between the two?
https://youtu.be/iG6fr81xHKA

**Comment by CoorFun** [comment]
Thanks Iwis and ggravlingen, now I understand how does that work!
