### ISSUE TITLE
No color temperature setting on RGB bulb

### ISSUE THREAD

**Issue by FezVrasta** [ggravlingen/pytradfri#177]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant

### Version of pytradfri
5.5.1

### Expected behaviour
My IKEA Tradfri RGB light should support color temperature setting

### Actual behaviour
No color temperature setting is available, only RGB is supported.

Related Home Assistant issue:
https://github.com/home-assistant/home-assistant/issues/14554

I'm using the RGB bulb through DeCONZ, my Tradfri bulbs that only support color temperature work just fine.

**Comment by ggravlingen** [comment]
I'm slighly confused here, are you using the Tradfri gateway or the DeCONZ USB stick to communicate with your bulbs?

**Comment by FezVrasta** [comment]
I'm using the DeCONZ RaspBee module. Sorry I now see pytradfri just communicates to the Ikea gateway, I thought it was a more broad tool since my issue got closed pointing to an update to this library 🙄

**Comment by FezVrasta** [comment]
Edit: actually, that specific bulb is using the Hue bridge, lol... what a mess

**Comment by ggravlingen** [comment]
No worries! 😃 

(Yes, we only communicate with the Gateway. DeCONZ is maintained by a separate organization.)
