### ISSUE TITLE
auto-detect if libcoap or aiocoap can be used

### ISSUE THREAD

**Issue by brean** [ggravlingen/pytradfri#179]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Windows 10

### Version of pytradfri
master

### Expected behaviour
We should check first if either coap-client or [aiocap](https://github.com/chrysn/aiocoap/) is installed and automatically decide which API to use and show an error message if we can not find any of them.

### Actual behaviour
Right now the debug-example uses libcoap_api.py which tries to run coap-client via subrpocess.
So I am just getting a cryptographic error message that some file does not exist when I try to run the pytradfri-examples in Windows (I guess I could try to compile coap-client, but a `pip install aiocoap` has less efford).

**Comment by lwis** [comment]
This isn't possible due to the the Python API and structure of your application being different for sync and async.
