### ISSUE TITLE
[discussion] Subscribing to lamp changes

### ISSUE THREAD

**Issue by Lakitna** [ggravlingen/pytradfri#180]
So I'm running into some issues, and I'm running out of ideas as to what it could be. I'm hoping you guys can give me some new insights.

I'm running Pytradfri sync standalone on a Raspberry Pi 3b with a daemon thread per lamp to subscribe to its changes and hold the change message until the main thread is ready to process them. The thread utilises Pytradfri's observe function, the one found in the examples with a timeout of 30 minutes. But I'm running into an issue where threads will crash without any error, warning, or anything making my application unresponsive. They do so at seemingly random moments, which is why I tried logging the behaviour (see below).

Since I'm getting pretty annoyed here and feel like I've tried everything I'm asking for your help here, even though this probably isn't a Pytradfri issue.

At this point, I'm open to major architectural changes as well as simple tweaks. Basically, just *anything* to make it work. 

This is my current implementation. Because of the issues I've been having there's a lot of logging and stuff in there. The only thing the logging is good for, is to verify that it, indeed, is unresponsive. Not terribly usefull.
```python
class ObserverThread(threading.Thread):
    def __init__(self, threadID, device):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = "Thread-%d" % threadID
        self.daemon = True
        self.device = device
        self.logFile = "Thread-%s" % self.device.name

    def run(self):
        """Thread runtime"""
        while True:
            try:
                metrics['thread started'] += 1
                log.blind("[time] >>", self.logFile, end="")
                api(self.device.observe(self._callback,
                                        self._err_callback,
                                        duration=(1800 + self.threadID)))
                log.blind("<< [time]", self.logFile)
                time.sleep(.01)  # Stability delay
            except:
                log.blind("E", self.logFile)
                print("Unexpected error:", sys.exc_info()[0])

    def _callback(self, device):
        """Lamp change callback"""
        self.device = device
        metrics['thread callback'] += 1
        log.blind("!", self.logFile, end="")
        # print("Received message for: %s" % self.device)

    def _err_callback(self, err):
        """Observing stopped callback"""
        metrics['thread stopped'] += 1
        log.blind("X", self.logFile, end="")


def setup():
    """
    Setup observing threads and return the first lampData
    """
    log("Subscribing to lamp changes: ", end="", flush=True)
    for i in range(len(light_objects)):
        thread = ObserverThread(i, light_objects[i])
        thread.start()

        threadList.append(thread)
        metrics['threads'].append(thread.device.name)
        time.sleep(0.2)  # Stability delay

    log.success("Done")
    log()
    return poll(True)
```

For the sake of being complete, the following is one of the daily thread specific logs. Very inconsistent, not the output I expected at all. This thread didn't crash during the day of the log.
```
06:30:01 >>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!X<< 07:00:31
07:00:31 >>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!X<< 08:42:48
08:42:48 >>!!!X<< 22:09:17
22:09:17 >>!!!X<< 23:23:04
23:23:04 >>!!!!!!X<< 23:53:07
```

**Comment by lwis** [comment]
I've never found libcoap observation to be stable. Have you given aiocoap a
try?

**Comment by Lakitna** [comment]
No, not yet for it would require some major refactoring throughout the application. It's not something I'd like to do if I'm not pretty sure it'll help.

**Comment by ggravlingen** [comment]
There hasn't been any activity in here for a good while. Closing issue, please feel free to reopen.
