### ISSUE TITLE
Support for multiple gateways wanted | user in issue willing to donate for a dev to buy a second gateway

### ISSUE THREAD

**Issue by ggravlingen** [ggravlingen/pytradfri#185]
#176 discusses that there is no support for multiple gateways in pytradfri. If you're out of things to do, we would appreciate if you could add such support and submit a PR.

**Comment by linuxlurak** [comment]
Link Collection:
https://github.com/home-assistant/home-assistant/issues/15231
https://github.com/home-assistant/home-assistant/issues/15287
https://github.com/ggravlingen/pytradfri/issues/176

perhaps here too:
https://github.com/chrysn/aiocoap/issues/98
https://github.com/chrysn/aiocoap/issues/97

and this in hass community:
https://community.home-assistant.io/t/multiple-ikea-traadfri-gateways-how/68119
https://community.home-assistant.io/t/correct-yaml-for-multiple-tradfri-gateways/58522

**Comment by YoinkZed** [comment]
Any news on implementing the possibility to have multiple Ikea gateways in your hassio setup?

**Comment by ggravlingen** [comment]
I dont think anyone is working on it.

**Comment by YoinkZed** [comment]
That's too bad :(.
How can we upvote this or do something?

What can I do?

**Comment by ggravlingen** [comment]
What's needed is a developer with two gateways. Unfortunately, none of the maintainers of this repo has this setup so we need to wait for someone in the community to reach out. Hence the `help wanted` label on this issue.

**Comment by linuxlurak** [comment]
If you are a developer please send me a message with your details and I donate a second gateway to you (Paypal, SEPA or anything else).

**Comment by ggravlingen** [comment]
@linuxlurak perhaps it would be a good idea to also post in the HA user forums pointing to this issue?

**Comment by linuxlurak** [comment]
I offered a donation here last summer https://github.com/home-assistant/home-assistant/issues/15287#issuecomment-405079700. Your are absolutely right, I'll create a new post in the HA user forums. Hopefully there is more publicity and we find an interested dev ;)

**Comment by ggravlingen** [comment]
I also made a post in the HA devs chat channel

**Comment by lwis** [comment]
This is still an issue with aiocoap due to the authentication method currently used for DTLS. Once that's fixed, this will be trivial.

**Comment by YoinkZed** [comment]
Have you seen this? Maybe this can help some people, if it is a matter of signal range:

https://m2.ikea.com/ca/en/p/tradfri-signal-repeater-30400407/

**Comment by sthorsen** [comment]
@linuxlurak hi do you still need someone with 2 gateways?
