### ISSUE TITLE
Unnecessary duplicate?

### ISSUE THREAD

**Issue by 42B** [ggravlingen/pytradfri#197]
https://github.com/ggravlingen/pytradfri/blob/3e3d68fb5b14c497b45548085778261fbd3c0ff7/pytradfri/const.py#L40

https://github.com/ggravlingen/pytradfri/blob/3e3d68fb5b14c497b45548085778261fbd3c0ff7/pytradfri/const.py#L63

Simple fix but I wasn't sure if there was any preference to one line being removed over the other so I made a quick issue first.

**Comment by ggravlingen** [comment]
Well spotted! There should definitely only be one so please feel free to submit a PR.

**Comment by 42B** [comment]
@ggravlingen ,

Sure, no problem! Should I just guess on which one to take?
