### ISSUE TITLE
[Research] Support for observing/subscribe/streaming?

### ISSUE THREAD

**Issue by lwis** [ggravlingen/pytradfri#2]
`aiocoap` has plenty of examples, one of them being;

https://github.com/chrysn/aiocoap/blob/master/clientGET-observe.py

**Comment by kmjonsson** [comment]
The problem with aiocoap is the lack of DTLS-support. See: https://github.com/chrysn/aiocoap/issues/67

The coap-client has observe support as well (-s). They call it subscribe but as far as I understand from the specification this is the same thing.

**Comment by lwis** [comment]
@kmjonsson Good point. I'm going to try and get hold of some bulbs and a gateway to test out observing, but it may be a while so if anyone else can confirm it's working then we can start development.

**Comment by kmjonsson** [comment]
@lwis, yes it works. It will leave the coap-client running and pop out new messages if there are changes. This also includes the switches so they can be used within HA (or other) as triggers for any event.
I guess it also includes groups, and other types of GET commands like /.well-known/core etc..

Popping out a observing/subscribing thread for each bulb/switch/thing might be a little silly but until there are a native coap library with dtls support this might be the best thing.

If you need som sample output I can provide it but I'm currently unavailable for doing coding but I will try to do some testing.

**Comment by balloob** [comment]
The app is able to do it and I doubt that it would open an observe channel for each bulb/group but I haven't explored the API that much beyond the basics yet.

**Comment by kmjonsson** [comment]
@balloob, it looks like the COAP observe/subscribe works like that. But the app only needs to observe things that are currently "active".

**Comment by balloob** [comment]
@kmjonsson you're right! Adding `-s <duration>`, ie `-s 50` and point it at a light allowed me to stream updates. This is awesome 🎉

**Comment by balloob** [comment]
Sadly, it still allows me to only stream one device at a time. There was a notifications endpoint `15006` but it only reports on notifications like loss of internet connectivity.

**Comment by balloob** [comment]
It means that we need to spin up X processes, one for each light 😞

**Comment by lwis** [comment]
Damn, a little more feasible if we had aiocoap - but that's not ready yet.

**Comment by rubenbe** [comment]
@balloob I guess a solution would be to integrate libcoap.so directly into python using e.g. cffi. As such we can support more complex use-cases (like listening to multiple devices) without having to spawn a process for each.

**Comment by lwis** [comment]
@rubenbe I'm of the opinion that those efforts would be better spent enhancing the incompatibilities with aiocoap (progress seems to have stalled)

**Comment by balloob** [comment]
I agree that I don't want to go down the path of integrating with `libcoap.so`. The compile issues to keep this supported on each platform will be too much effort.
