### ISSUE TITLE
pytradfri fails to configure gateway

### ISSUE THREAD

**Issue by suppnet** [ggravlingen/pytradfri#204]
I'm using lastest pytradfri version with Home Assistant. 
The IKEA gateway version is 1.4.15.
While trying to add/configure the gateway using HA web interface after enter security code I'm getting:
"Unknown error occurred"
And using shell and "python3 -i -m pytradfri 192.168.1.2" I get this:

[...cut...]
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.1.2 get ['15001', 65537]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pytradfri/__main__.py", line 63, in <module>
    devices = api(devices_commands)
  File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/libcoap_api.py", line 101, in request
    result = self._execute(api_command, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/libcoap_api.py", line 83, in _execute
    return_value = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1554, in _communicate
    self.stdout.errors)
  File "/usr/lib/python3.6/subprocess.py", line 740, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 27: ordinal not in range(128)

Is something changed recently cause I had previously configured other gateways in similar setup and it was working OK.

br.

**Comment by ggravlingen** [comment]
What are your devices named in the app? Any special chars?

**Comment by suppnet** [comment]
I didn't noticed this before but if you are adding the devices with their default names in some local language, these names are "magically" translated after language change in the app. But if you change any character in the default name while adding the device the name stays in language that was added. That's why first White spectrum panel is changing the name after the language change but the second White spectrum panel stays in polish language because I've manually added a digit 2 to the default proposed name. Weird, isn't it? 

btw your suggestion helped, now it's OK, thanks!!

br.

**Comment by suppnet** [comment]
I need to update the status, while the command line pytradfri works, HA is showing the same "Unknown error occurred" when I'm trying to configure the gateway:

Nov 11 15:15:10 odroid2 hass[5423]: 2018-11-11 15:15:10 ERROR (MainThread) [aiohttp.server] Error handling request
Nov 11 15:15:10 odroid2 hass[5423]: Traceback (most recent call last):
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 390, in start
Nov 11 15:15:10 odroid2 hass[5423]:     resp = await self._request_handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 366, in _handle
Nov 11 15:15:10 odroid2 hass[5423]:     resp = await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py", line 106, in impl
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/static.py", line 66, in staticresource_middleware
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/real_ip.py", line 34, in real_ip_middleware
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/ban.py", line 66, in ban_middleware
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/auth.py", line 68, in auth_middleware
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/real_ip.py", line 34, in real_ip_middleware
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/ban.py", line 66, in ban_middleware
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/auth.py", line 68, in auth_middleware
Nov 11 15:15:10 odroid2 hass[5423]:     return await handler(request)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/view.py", line 113, in handle
Nov 11 15:15:10 odroid2 hass[5423]:     result = await result
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/http/data_validator.py", line 47, in wrapper
Nov 11 15:15:10 odroid2 hass[5423]:     result = await method(view, request, *args, **kwargs)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/data_entry_flow.py", line 86, in post
Nov 11 15:15:10 odroid2 hass[5423]:     result = await self._flow_mgr.async_configure(flow_id, data)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/data_entry_flow.py", line 80, in async_configure
Nov 11 15:15:10 odroid2 hass[5423]:     flow, step_id, user_input)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/data_entry_flow.py", line 98, in _async_handle_step
Nov 11 15:15:10 odroid2 hass[5423]:     result = await getattr(flow, method)(user_input)  # type: Dict
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/tradfri/config_flow.py", line 51, in async_step_auth
Nov 11 15:15:10 odroid2 hass[5423]:     user_input[KEY_SECURITY_CODE])
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/tradfri/config_flow.py", line 148, in authenticate
Nov 11 15:15:10 odroid2 hass[5423]:     key = await api_factory.generate_psk(security_code)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 196, in generate_psk
Nov 11 15:15:10 odroid2 hass[5423]:     self._psk = yield from self.request(command)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 152, in request
Nov 11 15:15:10 odroid2 hass[5423]:     result = yield from self._execute(api_commands)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 142, in _execute
Nov 11 15:15:10 odroid2 hass[5423]:     _, res = yield from self._get_response(msg)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 90, in _get_response
Nov 11 15:15:10 odroid2 hass[5423]:     protocol = yield from self._get_protocol()
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 71, in _get_protocol
Nov 11 15:15:10 odroid2 hass[5423]:     return (yield from self._protocol)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/aiocoap/protocol.py", line 528, in create_client_context
Nov 11 15:15:10 odroid2 hass[5423]:     self.transport_endpoints.append((yield from TransportEndpointUDP6.create_client_transport_endpoint(new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop, dump_to=dump_to)))
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/aiocoap/transports/udp6.py", line 191, in create_client_transport_endpoint
Nov 11 15:15:10 odroid2 hass[5423]:     sock = socket.socket(family=socket.AF_INET6, type=socket.SOCK_DGRAM)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/lib/python3.6/socket.py", line 144, in __init__
Nov 11 15:15:10 odroid2 hass[5423]:     _socket.socket.__init__(self, family, type, proto, fileno)
Nov 11 15:15:10 odroid2 hass[5423]: OSError: [Errno 97] Address family not supported by protocol

Do you think this is somehow related or I've messed up something?

br.

**Comment by ggravlingen** [comment]
There's a reference in the traceback that indicates ipv6. Are you running that by an  chance?

**Comment by suppnet** [comment]
Nope, no IPv6 here:

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.12.255
        ether 00:1e:06:33:28:64  txqueuelen 1000  (Ethernet)
        RX packets 32680  bytes 8040237 (8.0 MB)
        RX errors 0  dropped 916  overruns 0  frame 0
        TX packets 19722  bytes 4203551 (4.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 40  

as you can see no inet6 line in the output of ifconfig so no ipv6. Is that a problem?

br.

**Comment by suppnet** [comment]
Problem solved:
[https://github.com/chrysn/aiocoap/issues/129](url)
