### ISSUE TITLE
rgbcct

### ISSUE THREAD

**Issue by camatthew** [ggravlingen/pytradfri#209]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
diyhue

### Version of pytradfri
latest
### Expected behaviour
white leds turn on when i change the temputure.
### Actual behaviour
only the rgb replicates the color tempetures

**Comment by ggravlingen** [comment]
I'm not quite following here, is `diyhue` using `pytradfri`? I couldn't find any references to it in that lib.

**Comment by ggravlingen** [comment]
Closing issue as it seems to be placed in the wrong repo.
