### ISSUE TITLE
Maybe some usefull information

### ISSUE THREAD

**Issue by rbraken** [ggravlingen/pytradfri#211]
Hi,

I did some sniffing of the ikea app, and found some interesting behaviour.
It might be usefull to enhance pytradfri.

I wanted to put a light bulb into two different groups. ZLL allows for this, but the app would not let me do this.
The following coap command will add a group to a bulb:

coap-client -u pytradfri -k psk  -m put  -t json coaps://10.10.10.200:5684/15004/add -e '{"9003":[65576],"9038":147497}
In this command:
psk must be replaced with the key
10.10.10.200 is my gateway IP.
65576 is a bulb.id.
147497 is a group.id. 

You can replace add with remove to delete a group from a device.

If you replace (9038) with 9001 : "string" (ATTR_NAME)
A group with the name "string" is also created.

Maybe usefull ????

Greetinrg René

**Comment by ggravlingen** [comment]
Thank you for sharing your findings! Am I correct in understanding that by using your code above, you can add a device to two groups?

**Comment by rbraken** [comment]
Yes, exactly, one device in multiple groups, no problem at all.
 
Some more:

coap-client -u pytradfri -k psk -v 1 -m post  -t json  coaps://10.10.10.200:5684/15005/147498 -e '{"9058":1,"9001":"a123"}' 

will store the current status of the group (bulbs) as a scene (mood=a123)
9058 == scene_activate_flag
see the keywords used by current app
[keywords.txt](https://github.com/ggravlingen/pytradfri/files/2636811/keywords.txt)


The next one will delete a scene:
coap-client -u pytradfri -k psk 
-v 1 -m delete  -t json  coaps://10.10.10.200:5684/15005/147498/223639
