### ISSUE TITLE
Random RequestTimeouts

### ISSUE THREAD

**Issue by dio5** [ggravlingen/pytradfri#213]
Is anybody else getting random timeouts?

Even with using the sync example, it times out regularly and I have not found a pattern.

return self._execute(api_commands, timeout=timeout)
  File "xxxxx/venv/lib/python3.5/site-packages/pytradfri/api/libcoap_api.py", line 85, in _execute
    raise RequestTimeout() from None
pytradfri.error.RequestTimeout

Just to be clear, it works fine and I don't think it is related to the code here, it's just that it seems totally unstable?

**Comment by ggravlingen** [comment]
#208 is seeking to improve stability

**Comment by dio5** [comment]
Hmm, is that gonna help with this?

```
  devices = api_request(devices_commands)
  File "/xxxxxx/venv/lib/python3.5/site-packages/pytradfri/api/libcoap_api.py", line 101, in request
    result = self._execute(api_command, timeout=timeout)
  File "/xxxxxx/venv/lib/python3.5/site-packages/pytradfri/api/libcoap_api.py", line 85, in _execute
    raise RequestTimeout() from None
pytradfri.error.RequestTimeout
```

lines 82-85 in libcoap_api:

```
 try:
            return_value = subprocess.check_output(command, **kwargs)
        except subprocess.TimeoutExpired:
            raise RequestTimeout() from None

```
This is not on observations, but on getting the devices.

**Comment by dio5** [comment]
No, I haven't tried the other one yet. But, now that I'm running my app from a pi and not from my laptop anymore, it doesn't seem to happen that frequently. I've also created a callback in the rare case it happens so it's not really an issue anymore.

I think it must be something with my local environment.

**Comment by ggravlingen** [comment]
Ok, closing the issue.
