### ISSUE TITLE
failure on initial contact

### ISSUE THREAD

**Issue by Julf** [ggravlingen/pytradfri#215]
Stand-alone use. 
Ping works just fine, but:
```python3 -i -m pytradfri nnn.nnn.nnn.nnn
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
Please provide the 'Security Code' on the back of your Tradfri gateway:  xxxxx
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
DEBUG:pytradfri.api.libcoap_api:Executing nnn.nnn.nnn.nnn post ['15011', '9063']: {'9090': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
DEBUG:pytradfri.api.libcoap_api:Received: v:1 t:CON c:POST i:24f3 {} [ ]
{"9091":"xxxxxxxxxxxxxxxxxxxxxx","9029":"1.4.0015"}
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 48, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 164, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 90, in _execute
    api_command.result = _process_output(return_value, parse_json)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 195, in _process_output
    return json.loads(output)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ggravlingen** [comment]
Does it work if you run the lib from docker?

**Comment by Julf** [comment]
Haven't tried yet. Is there a docker image somewhere? Seems the download tar file doesn't contain the "./script/dev_docker" script.

**Comment by ggravlingen** [comment]
Yes, there are docker images in the root folder that are run using the mentioned script. The tar ball only contains files needed to run the lib from within Python. so you need to clone this repo to get the docker files.

**Comment by ggravlingen** [comment]
Also, what's the content of the `tradfri_standalone_psk.conf` file? I suggest redacting the key before posting here.

**Comment by Julf** [comment]
Docker on raspbian seems to be a bit of an issue. Where is tradfri_standalone_psk.conf supposed to live - I don't seem to be able to find it?

**Comment by ggravlingen** [comment]
In the same folder as where you clone the repo or run pytradfri from. Make sure you have read/write access in that folder as a file is created.

**Comment by ggravlingen** [comment]
Sounds like an error in your environment. Is the directory also writable by your user? What happens if you run as root?

**Comment by Julf** [comment]
Yes, ran it from (writeable) home directory, as root. No file created.

**Comment by ggravlingen** [comment]
I would also try running from Docker and make sure the key on the gateway is correctly written in. Other than that, I’m afraid I’m out of ideas.

**Comment by ggravlingen** [comment]
Sorry, I’m out of clues. It’s worked on my rpi3 in the past, at least in the docker.

**Comment by Julf** [comment]
Could it simply be the Trådfri base station is broken?

**Comment by ggravlingen** [comment]
If the app works I'm inclined to say the base station/gateway works.

**Comment by Julf** [comment]
I did have some connection issues with the app - I'll get back to you, travelling right now.

**Comment by ggravlingen** [comment]
After some discussion, we've come to the conclusion that there's not much we can do here but to keep the project up to date with the firmware: https://github.com/ggravlingen/pytradfri#known-issues

**Comment by Julf** [comment]
On 10-04-19 19:54, Patrik wrote:
> After some discussion, we've come to the conclusion that there's not
> much we can do here but to keep the project up to date with the
> firmware: https://github.com/ggravlingen/pytradfri#known-issues

OK, thanks for looking into it!

	Julf
