### ISSUE TITLE
light switch/dimmer changes do not change group state.

### ISSUE THREAD

**Issue by brean** [ggravlingen/pytradfri#217]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
stand-alone (Python 3.5 using Linux Fedora 29)

### Version of pytradfri
master (tested with libcoap and aiocoap)

### Expected behaviour
When I get the data from the groups, state should be `False` when the light is off and `True`when they are on.

### Actual behaviour
When I set the state to `False` in my code the lights go off, and getting the data after that it shows False as state correctly, but when I use a dimmer or the IKEA Tradfri App the state is still `False` and the dimmer values are above 0.

### Example code to get Tradfri state and dimmer values
I call this code every 5 seconds to update my UI:
```
    api = api_factory.request
    gateway = Gateway()
    groups_commands = api(gateway.get_groups())
    groups = api(gateway.get_groups())
    for group in groups:
        print(group.name, group.dimmer, group.state)  # shows False for group.state even if the lights are on
```

**Comment by brean** [comment]
also when i iterate over `group.member_ids`, get all devices with the ids and check if they are turned on I can say that the light is turned on:
```
for dev in devices:
    if dev.has_light_control:
        print(dev.light_control.lights[0].state)  # returns the right current state of the single light bulb
```

**Comment by ggravlingen** [comment]
Please see this issue: https://github.com/ggravlingen/pytradfri/issues/216

**Comment by brean** [comment]
Thank You!
