### ISSUE TITLE
list of api commands in wiki

### ISSUE THREAD

**Issue by nightcatnl** [ggravlingen/pytradfri#223]
### Where are you using pytradfri
standalone

### Version of pytradfri
current sync version

### Actual behaviour

Can't there be a list of api commands added to the wiki or docs included in the package.
I am trying to simply switch on and off sockets from my pi though can't find the commands to do so.
Using the sync version

**Comment by ggravlingen** [comment]
Hi,

Please have a look at the example script and see if it is of any help. If not, I'll try to help you with the commands needed.
https://github.com/ggravlingen/pytradfri/blob/b122263179cce00b70d505c4cb688e77a6613f51/examples/example_socket_async.py#L111

**Comment by ggravlingen** [comment]
No reply for a long while, closing issue.
