### ISSUE TITLE
Add support for Tradfri On/Off remote E1743

### ISSUE THREAD

**Issue by jdeluyck** [ggravlingen/pytradfri#227]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant 0.89.1

Currently, there seems to be no support within ZHA / HA for the Ikea Tradfri On/Off remote (model e1743) that comes packaged with some Tradfri power sockets.

I can perfectly pair the power socket, but not the remote, so I cannot have the power socket controlled by both the remote and HA (which is what I need)

Looking around, I came across issues on the zigbee2mqtt tracker about this issue and the fact that they needed to add support

https://github.com/Koenkk/zigbee2mqtt/issues/102
https://github.com/Koenkk/zigbee2mqtt/issues/997

I don't know what needs to happen to add the support? If i can help in any way?

Kind regards

**Comment by lwis** [comment]
This isn't something the gateway supports, which is what pytradfri models. If you want to use the button you can still pair it with the outlet.

**Comment by jdeluyck** [comment]
That's a pity. It does work with the remote that I use to control the lamps (rgb lamps), that one I can pair both to the lamps and to my HA installation.

**Comment by tiagofreire-pt** [comment]
I was able to pair the button on the last version of zigbee2mqtt and hassio.

**Comment by ggravlingen** [comment]
The zigbee2mqtt project doesn’t run on the Trådfri gateway. It still doesn’t work on the Trådfri gateway I’m afraid.
