### ISSUE TITLE
Can pytradfri be used to react when a remote control button was pressed?

### ISSUE THREAD

**Issue by kalsan** [ggravlingen/pytradfri#234]
I have only read but never actually played around with the TRADFRI gateway or any other LightLink gateway device. Before I spend money on a new semi-DIY lighting system, please allow me to ask a potentially stupid question: Is it possible to use pytradfri to be notified when a TRADFRI remote control such as https://www.ikea.com/ch/en/catalog/products/30338849/ sends a command?

As an example, consider a setup where a Raspberry Pi is connected to a TRADFRI gateway coupled to a remote control, as well as to a speaker. The Pi plays music and I can control the playback through python (this could be achieved by running mpc from within python). Can I use pytradfri such that an arbitrary Python function (skipping to the next song) is called whenever the "right" button is pressed on a particular remote? 

I haven't found any blogs or examples illustrating such a scenario and I'd be greatly helped in my understanding of TRADFRI if this answer was answered.

**Comment by ggravlingen** [comment]
The short answer to your question is: no. The reason for this is that the gateway does not catch button presses, so it's not possible. If this is an important feature for you, I would recommend looking into buying a Conbee USB-stick and configure it using, for instance, [Home Assistant](https://www.home-assistant.io/).

**Comment by kalsan** [comment]
Thanks a lot! Much appreciated.
