### ISSUE TITLE
Set color for groups

### ISSUE THREAD

**Issue by kjlisby** [ggravlingen/pytradfri#236]
### Version of  pytradfri 6.0.1

The IKEA app is able to set color for groups, if at least one device in the group supports it.

I suggest to implement the same in  pytradfri. In fact why not just allowing it for all groups?

**Comment by kjlisby** [comment]
I have implemented this in the simplest way I could imagine. However, I need you not only to merge my pull request, but also to issue a new pip packet, so that it is useable from the IKEA Trådfri plugin for Domoticz. I can see that it is a while ago the latest pip package was made available. Have you stopped releasing through pip?

**Comment by ggravlingen** [comment]
@kjlisby: I'll release it to pip once merged.
