### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by heggink** [ggravlingen/pytradfri#241]
I am using Moroen's python plugin for domoticz which uses the pytradfri library
I have everying (coap, pytradfri, plugin) updated to the latest versions.
The issue I face is that, after a while, I can no long access the gateway and get a timeout error (ERROR:root:Error in initGateway: Request timeout) even though the gateway is pingable and the IKEA app has no issues with it (connevts and I can switch devices). Generating a new key pair also times out.
Power cycling the bridge makes it return to 'normal'.
The bridge is running the latest 1.10.1 firmware.
Any idea what is causing this?

**Comment by ggravlingen** [comment]
Please see this in the readme: https://github.com/ggravlingen/pytradfri#known-issues

**Comment by heggink** [comment]
Understood. Three thing is that I have had the plugin running for quite a while with no issues at all until recently. It's as if the newer firmware creates issues... That's why I wondered if moving the hub would make any difference since there were no problems before and only the firmware changed.

**Comment by ggravlingen** [comment]
Unfortunately, there's nothing that can be done from our side here. Closing the issue.
