### ISSUE TITLE
Control outlets: "AttributeError: 'bool' object has no attribute 'observe'"

### ISSUE THREAD

**Issue by hessius** [ggravlingen/pytradfri#245]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Standalone: Both scripted and in CLI mode.

### Version of pytradfri
6.3.0

### Expected behaviour
Turn sockets on / off
### Actual behaviour
I'm getting an error that looks like the one mentioned in #182, trying to run pytradfri to control an outlet, both in CLI mode and in a script I'm getting "AttributeError: 'bool' object has no attribute 'observe'".

### Steps to reproduce
Launch CLI mode and execute the following:
>sockets = [dev for dev in devices if dev.has_socket_control]
>state_command = sockets[0].socket_control.set_state = False
>api(state_command)

Generates the error message:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/home/pi/.local/lib/python3.5/site-packages/pytradfri/api/libcoap_api.py", line 49, in _execute
    if api_command.observe:
AttributeError: 'bool' object has no attribute 'observe'
`

## Note
Listing of devices / sockets, as well as their states is working without issue.

**Comment by lwis** [comment]
`state_command = sockets[0].socket_control.set_state = False` the command you're passing to `api()` is the result of the assign - `False`.
