### ISSUE TITLE
Any suggestions how to run pytradfri after startup?

### ISSUE THREAD

**Issue by matzex** [ggravlingen/pytradfri#252]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
raspberry pi, stand-alone

### Version of pytradfri
6.3.1
### Expected behaviour
Use cronjobs to start example_sync.py on startup with
`@reboot python3 example_sync.py GATEWAY-IP`

### Actual behaviour
I have multiple errors when starting a python script with pytradfri from a cronjob. Do you have any suggestions how to run a python script with pytradfri on raspberry pi in a headless mode at every reboot/startup of the system?

**Comment by lwis** [comment]
Hi, the purpose of this project is to provide a library for integration into other projects/scripts/applications. The example scripts provided are intended to showcase the functionality of the library, not to be run regularly - or all the time.
