### ISSUE TITLE
Missing battery state for Fyrtur & Kadrilj 

### ISSUE THREAD

**Issue by onkelbeh** [ggravlingen/pytradfri#256]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant 0.102.0_beta1

### Version of pytradfri
pytradfri-6.4.0

### Expected behaviour
Blinds should report battery level

### Actual behaviour
Blind do not show battery level:
<img width="1134" alt="Bildschirmfoto 2019-11-17 um 22 46 04" src="https://user-images.githubusercontent.com/42828703/69014582-eaa4e280-098b-11ea-8aad-b38aca3628a7.png">

If help/testing is needed, just drop me a note.

**Comment by ggravlingen** [comment]
The battery state is supported by pytradfri. Getting it to work in Home Assistant has proved to be a bit more tricky, but that's a discussion for the HA Github repo. Closing this issue.
