### ISSUE TITLE
`RequestError` when running demo

### ISSUE THREAD

**Issue by kostrykin** [ggravlingen/pytradfri#259]
The basic test `python3 -i -m pytradfri 192.168.0.2` prompts for the IP address, then crashes with following error:
```
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
Please provide the 'Security Code' on the back of your Tradfri gateway: ****************
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.0.2 post ['15011', '9063']: {'9090': '********************************'}
Traceback (most recent call last):
  File "/home/void/.anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/void/.anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/pytradfri/pytradfri/__main__.py", line 48, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/tmp/pytradfri/pytradfri/api/libcoap_api.py", line 164, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/tmp/pytradfri/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/tmp/pytradfri/pytradfri/api/libcoap_api.py", line 88, in _execute
    'Error executing request: {}'.format(err)) from None
pytradfri.error.RequestError: Error executing request: Command '['coap-client', '-u', 'Client_identity', '-k', '****************', '-v', '0', '-m', 'post', '-f', '-', 'coaps://192.168.0.2:5684/15011/9063']' returned non-zero exit status 1.
```
From what I understand from the other issues reported here, there is supposed to be a file `tradfri_standalone_psk.conf` to be created in the working directory. However, no such file is created anywhere. I've tried running as root too. I'm using Ubuntu 18.04.

### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
stand-alone

### Version of pytradfri
the same error occurs with both version 6.4.0 installed from PIP and the current `master` branch version

**Comment by ggravlingen** [comment]
Hi, have you installed the requirements for the lib, eg `coap-client`?

**Comment by sasreim** [comment]
Hi,

same issue here.
Installed libcoap using the provided script.
RequestError after Security Code has been entered.

**Comment by ggravlingen** [comment]
What happens if you run the command coap-client in shell?

**Comment by sasreim** [comment]
I can't get any useful response when using the "-f -" option independent of the input.
If I provide any file in the command the response is "EMRG coaps URI scheme not supported in this version of libcoap"

coap-client v4.3.0alpha -- a small CoAP implementation
(libcoap-develop branch)

**Comment by kathagor** [comment]
Hi,

same problem here. I think its a problem with the gateway/firmware.
Tried it with pytradfri, because I had trouble to set up Tradfri with openHab and ioBroker.
All implementations have the problem to obtain the pre-shared key and the identity. Tested ist with two gateways and also at a frinds home, who is running Tradfri with ioBroker sinc early 2019. Nothing worked.

One interresting thing. If you try connecting the android app to the gateway:
- Works with the QR code.
- Does not work mit the serial and security code entered manual.
Checked data in the QR code. It is the same like the printed code.

**Comment by aahlborg** [comment]
I had the same problem and I found a solution [here](https://www.domoticz.com/forum/viewtopic.php?t=17312&start=240#p178183).

In short: The official Ubuntu libcoap2 didn't work with pytradfri so I had to install it manually.

**Comment by kostrykin** [comment]
> I had the same problem and I found a solution [here](https://www.domoticz.com/forum/viewtopic.php?t=17312&start=240#p178183).
> 
> In short: The official Ubuntu libcoap2 didn't work with pytradfri so I had to install it manually.

I confirm that, it works!
