### ISSUE TITLE
Increase maximum length of shade to >100

### ISSUE THREAD

**Issue by rummens** [ggravlingen/pytradfri#264]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
standalone
### Version of pytradfri
latest, master branch as of now
### Expected behaviour
Ability to close blind over its maximum limit
### Actual behaviour
Increasing the state value to >100 throws server error.

### Explanation 
I know this is not a limitation of pytradfri but more of the blind itself, but maybe I am overseeing something. My problem is that my windows are higher than 195cm. My idea was to use the existing/old blinds and transfuse the fabric onto the new Ikea one. However Fyrtur stops after its maximum length has been reached, which would in my case only cover 75% of the window. The limit seems to be hardcoded into the unit.

I was hopping to somehow override this behaviour with software but as far as I can see there is not way to tell the blind to keep opening above 100%. I tried many things and the only solution I came up with is to remove the battery once the blinds are at 100%, reseting it internally to 0%. Then one can tell it to open to 25%, covering the rest of the area. This however requires me to bridge the battery or somehow cut the power to the blinds every time I want to open/close it. 

Is there any other parameter one could use to workaround this? I did my test with _9003_ but nothing seems to happen with this one, the only parameter actually changeable seems to be _5536_.

Thanks

**Comment by ggravlingen** [comment]
We validate the value sent to pytradfri and make sure it's in the range of [0, 100]. I'm pretty sure though that the gateway won't do anything to values outside of that range as I expect the Fyrtur device to be setup with a maximum range. Please feel free to validate using a raw coap command instead of pytradfri.

Closing issue as it's not really related to the functionality of this library.

**Comment by rummens** [comment]
Yes I tried this and indeed every value above 100 is rejected. Any other thing I could try or could you point me to more documentation about the gateway's "API"?

**Comment by ggravlingen** [comment]
The API is IKEA’s internal one and there are no docs in the public domain as far as I know.

What we’ve done here is reverse-engineering and adding a Python layer to it.

Worth noting that the firmware in the Fyrtur might also have cap of 100 so hacking the gateway is not necessarily going to help.

**Comment by rummens** [comment]
Yes it seems the limit is hardcoded into the firmware 😐

Anyway thanks for your reply and for this project, working great for normal use cases.
