### ISSUE TITLE
Example of long running integration in a web app

### ISSUE THREAD

**Issue by niklasastrom** [ggravlingen/pytradfri#268]
Hello, 

I am struggling to run the library in a good way in my webapp that I am using for my custom built home control application that I am working on.
I am currently running an aiohttp server exposing websockets that push the tradfri values to the clients, but I can't run the tradfri library in a good way. I am starting the tradfri connection to the gateway (async mode), similar as to in the example, but instead of the `asyncio.get_event_loop().run_until_complete(run())` from the example, I am running an endless loop in my tradfri class 
```
        while True:
            await asyncio.sleep(0)
```
to be able to keep the tradfri connection open and receive callbacks from the gateway when light values change. This works, but I assume it is not too good and that the loop thread is still running when the client reconnects (from a browser refresh for example), because I can see that the CPU and memory usage of the python app is increasing over time.

Is there any examples on how to run the integration to the gateway to be able to receive callbacks when lights are being updated without using a set timer like in the example? I want to listen so changes as long as as a client is connected to the server (or as long as the server is running if that is easiers..).

I appreciate some input and help! I am new to python and the async libraries, so I might miss some basic things here.. :)

**Comment by voelkerb** [comment]
Hey,

some news on this? I am also interested in an endless loop example.

**Comment by balloob** [comment]
Start it with your application and shut it down with your application. Just like the web server.

See Home Assistant for an example https://github.com/home-assistant/core/blob/dev/homeassistant/components/tradfri/__init__.py#L99-L109
