### ISSUE TITLE
Does the blind support stop/pause now?

### ISSUE THREAD

**Issue by blair287** [ggravlingen/pytradfri#272]
Using the ikea blind on ZHA at the moment but it's terrible but one bit I not sure about if I get tradfri hub is does HA have the ability to stop the blind or only up and down?

**Comment by xorbital** [comment]
Yes. What works:
- open/close blind
- stop blind
- show current position (updated very quickly)
- set cover position

What doesn't work:
- Cover closing/opening status home-assistant/core#37223
- Battery status home-assistant/core#28675

**Comment by ggravlingen** [comment]
Just to be clear, battery status also works in pytradfri but not in Home Assiatant unless a workaround with a custom component is used.

Closing this issue as the question relates to Home Assistant, which is a separate project.

**Comment by xorbital** [comment]
That's true, you can basically choose between battery status or position reporting in my experience.
