### ISSUE TITLE
PyTradfri 2.0: sans-io

### ISSUE THREAD

**Issue by balloob** [ggravlingen/pytradfri#29]
In the Python community there has been a movement to make Sans-IO libraries. For an intro, see [this talk by Cory Benfield at PyCon 2016](https://www.youtube.com/watch?v=7cC3_jGwl_U&).

The idea is to separate the parser from the actual sending/receiving of messages so that there can be different implementations. With aiocoap being on the horizon (#28), I want to transform the library to be able to both support a sync and async API.

The code is already organized in such a way that the migration will be fairly painless. All writing is already done via a single method: `set_values`. Instead of having our methods call the API directly, we will have it return a command object. We then have different APIs that we can give the command to.

The sync API would look like this:

```python
command = light.light_control.set_dimmer(100)
api(command)
```

If the API wants to consume the response from the command, we can have a callback method be added to the command that can automatically be called by an implementing API.

```python
command = light.update()
yield from api(command)
# Under the hood api calls `command.set_result(result)`
```

**Comment by Hedda** [comment]
@balloob Any news on movement to Sans-IO libraries?

**Comment by balloob** [comment]
Closed via https://github.com/ggravlingen/pytradfri/pull/34
