### ISSUE TITLE
Connect problem

### ISSUE THREAD

**Issue by gohm44** [ggravlingen/pytradfri#31]
Hi,
I sill get error when I run pytradfri
```
python3 -i -m pytradfri 192.168.1.167 <SECRET KEY>

DEBUG:pytradfri.coap_cli:Executing 192.168.1.167 get ['status']
DEBUG:pytradfri.coap_cli:Received: {}
DEBUG:pytradfri.coap_cli:Executing 192.168.1.167 get ['15001']
DEBUG:pytradfri.coap_cli:Received: []
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/__main__.py", line 22, in <module>
    light = lights[0]
IndexError: list index out of range
>>> lights
[]
>>> 
```
If i understand correctly I can connect to gateway but there is no chance to get list of lights. (I own 2 lights) I have tried reset of gateway several times. Also on some fresh installation... raspbian, raspbian lite, hassbian, ubuntu. Oryginally i was try to connect tradfri via home assistant which is using this modifided libcoap but also no succes. Home assistant accepted my security key and thats it... no error but also no lights :( I suppose that the isssue is libcoap.

**Comment by balloob** [comment]
> DEBUG:pytradfri.coap_cli:Executing 192.168.1.167 get ['15001']
> DEBUG:pytradfri.coap_cli:Received: []

This means that no lights have been received from your gateway.

**Comment by gohm44** [comment]
Yep I realized that :). I was struggle with that so hard. I did restart all devices again and then home assistant starts working with Tradfri. So I guess it was my mistake. Pairing devices maybe... nvm. My fault I am noob :) Anyway thanks for you answer! I appreciate it! btw home assistant It's great! thx
