### ISSUE TITLE
pytradfri.error.RequestTimeout when using pytradfri inside an infinite loop

### ISSUE THREAD

**Issue by mbuffat** [ggravlingen/pytradfri#38]
I am using the pytradfri lib in a daemon service that run on a pi  as an interface to my home automation system JEEDOM. 
Using either a pooling method, that check the gateway every 10 sec. or the new observe function (as in example_sync), after some time I get a timeout error:
```
File "/usr/local/lib/python3.4/dist-packages/pytradfri/api/lib
juin 21 09:00:25 jeedomGaule tradfridaemon.py[23714]: request(Command('get', ['status']))
juin 21 09:00:25 jeedomGaule tradfridaemon.py[23714]: File "/usr/local/lib/python3.4/dist-packages/pytradfri/api/lib
juin 21 09:00:25 jeedomGaule tradfridaemon.py[23714]: return _execute(api_commands[0])
juin 21 09:00:25 jeedomGaule tradfridaemon.py[23714]: File "/usr/local/lib/python3.4/dist-packages/pytradfri/api/lib
juin 21 09:00:25 jeedomGaule tradfridaemon.py[23714]: raise RequestTimeout() from None
juin 21 09:00:25 jeedomGaule tradfridaemon.py[23714]: pytradfri.error.RequestTimeout
```
and I had to unplug the gateway to be able to access it again.

- Maybe I am doing something wrong with pytradfri ?
- Are there a way to do a soft reset of the gateway (without libcoap) ?
- Another question is the value of the duration parameter in the device.observe ?
- Can I run it indefinitely ? I try 0 but I received  "Observing stopped" after some time. If I restart the thread, I get the  RequestTimeout error after some times

Thanks again for the lib
Marc

**Comment by lwis** [comment]
Hi Marc,

In my testing I found that libcoap does not support observations of longer than ~2 mins, aicoap does not suffer from this restriction.

Not sure why your gateway is crashing though, sorry.
