### ISSUE TITLE
Observe remotes/dimmers

### ISSUE THREAD

**Issue by nmaggioni** [ggravlingen/pytradfri#41]
Would it be possible to use the remotes and dimmers for generic use, by pairing them to the gateway and not to any bulb? Are the [remotes' activities](https://bitsex.net/software/2017/coap-endpoints-on-ikea-tradfri/) observable?

**Comment by lwis** [comment]
Remotes and sensors are currently not observable from the Gateway in our tests, you'd have to contact IKEA to see if it's something they're considering.
