### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'coap-client'

### ISSUE THREAD

**Issue by martikainen87** [ggravlingen/pytradfri#42]
Description: Using pytradfri from my homeassistant instance running in a python virtual environment on Ubuntu OS

**base OS:** Ubuntu 17.04 zesty
**Hass version:** 0.48.0
**Python version:** Python 3.5.3

I've followed the guide https://home-assistant.io/components/tradfri/ several times. Each time I've retried it ive uninstalled libtool, autconf and coap-client, with --purge, then executed a apt-get update and dist-upgrade command followed by a reboot. 

I can execute the command "coap-client" from both my regular user outside the virtal environment, and also when inside the virtual environment as my user "homeassistant" which runs hass. 

This is the error i receive as soon as i use the "configurator" in hass (entering my security code) or adding a tradfri.conf in my configuration folder for hass.

```

2017-07-03 12:25:31 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/tradfri.py", line 57, in configuration_callback
    DEFAULT_ALLOW_TRADFRI_GROUPS)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/tradfri.py", line 116, in _setup_gateway
    api = retry_timeout(cli_api_factory(host, key))
  File "/home/homeassistant/.homeassistant/deps/pytradfri/coap_cli.py", line 104, in api_factory
    request('get', ['status'])
  File "/home/homeassistant/.homeassistant/deps/pytradfri/coap_cli.py", line 56, in request
    return_value = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'coap-client'
```

```
(homeassistant) homeassistant@HomeAssistant:/usr/local/bin$ which coap-client
/usr/local/bin/coap-client
```
Running coap-client insite virtual environment 
```
(homeassistant) homeassistant@HomeAssistant:/usr/local/bin$ coap-client
coap-client v4.1.2 -- a small CoAP implementation
(c) 2010-2015 Olaf Bergmann <bergmann@tzi.org>

usage: coap-client [-A type...] [-t type] [-b [num,]size] [-B seconds] [-e text]
                [-m method] [-N] [-o file] [-P addr[:port]] [-p port]
                [-s duration] [-O num,text] [-T string] [-v num] [-a addr]

```
tried giving coap-client full access
```
(homeassistant) homeassistant@HomeAssistant:/usr/local/bin$ ls -color
total 640
-rwxr-xr-x 1 root    212 Jun 28 21:04 virtualenv
-rwxr-xr-x 1 root 208280 Jul  3 11:28 coap-server
-rwxr-xr-x 1 root 215936 Jul  3 11:28 coap-rd
-rwxrwxrwx 1 root 222464 Jul  3 12:23 coap-client

```

For troubleshooting I've also installed a completely fresh install of homeassistant on ubuntu 16.04, same errors.
I also have a docker version of hass running, inside that one everything works, but I did not configure the special coaplib for that one, it was already done in the image I guess. 

Let me know if you need more information!

**Comment by martikainen87** [comment]
I finally found the reason for my issues by misstake, I were troubleshooting another component (ICMP ping) and went deeper into permissions and PATH issues, it seems like I've added a line to my systemd service which disabled the use of my original OS path's

It was the rows with '#' before them, except the first row of course since thats an actual comment. 
I hope this might help someone else who's making stupid misstakes :wink:

[Unit]
Description=Home Assistant
After=network.target
[Service]
Type=simple
User=homeassistant
# Make sure the virtualenv Python binary is used
# Environment=VIRTUAL_ENV="/srv/homeassistant"
#Environment=PATH="$VIRTUAL_ENV/bin:$PATH"
ExecStart=/srv/homeassistant/bin/hass -c "/home/homeassistant/.homeassistant"

[Install]
WantedBy=multi-user.target

**Comment by balloob** [comment]
@martikainen87 please do not use the Home Assistant logo as your avatar.

**Comment by martikainen87** [comment]
Oh sorry Paulus, didnt even think that it would be seen anywhere since i rarely post with my githubaccount, its updated now :)
