### ISSUE TITLE
Add RGB support

### ISSUE THREAD

**Issue by r41d** [ggravlingen/pytradfri#50]
(same text as in [general Tradfri discussion](https://github.com/bwssytems/ha-bridge/issues/570#issuecomment-323758488))

Apparently E27 RGB bulbs are now available, today I bought one in an IKEA in Germany.
I didn't find **anything** online, so these gotta be released brand-new.
Here are some photos and screenshots: [http://imgur.com/a/yC5VW](CLICK)
The Android App is able to display the colors that the bulb shows, but it's not able to set them. Setting RGB color only works at the moment by repeatedly pressing the < and > buttons on the physical Tradfri remote.
Will try to do further investigation soon.

EDIT:
- Cycleable colors are: The three normal whites (cold, normal, warm), candlelight, warm amber, dark peach, saturated pink, light purple, light blue. (These color names are shown when you click on New Mood for a category which the RGB bulb is in.)

**Comment by ggravlingen** [comment]
Did you see this? https://github.com/ggravlingen/pytradfri/pull/48

**Comment by matemaciek** [comment]
As soon as I get RGB bulb I'll be able to add support to pytradfri. It's bringing me a lot off fun (-:

**Comment by schliflo** [comment]
@ggravlingen as i understand #48 it is just for the white tones (yellow-ish white to blue-ish white) - the bulbs @r41d mentions are full RGB.

**Comment by r41d** [comment]
@ggravlingen @schliflo correct. I saw the #48 PR earlier, but understood that it was only meant for white spectrum.
Now that IKEA actually released full RGB bulbs, it's the main question how to set arbitrary colors via the gateway :-)
See [my post from April](https://github.com/bwssytems/ha-bridge/issues/570#issuecomment-293905222) where I gathered some theories about the COLOR_X and COLOR_Y parameters, IKEA probably uses the CIE 1931 xy color space, but I think most people would like R, G and B values for their colors, a quick google led me [to this conversion method](http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html) :)

**Comment by lwis** [comment]
@r41d sounds like you're half way to a PR :wink:

**Comment by ggravlingen** [comment]
Great work guys! Closing this issue as it's been resolved through #51..
