### ISSUE TITLE
Error when no lights visible with only the remote control

### ISSUE THREAD

**Issue by rudyvan** [ggravlingen/pytradfri#59]
Hello,
i have a little test setup with one light and one remote control.
When the light was not visible for a while by the tradfri gateway, i got the following error when calling has_light_control:

File "/home/pi/PI_Drivers.py", line 272, in <listcomp>
ikea_drv.lights = [dev for dev in ikea_drv.devs if dev.has_light_control]

File "/usr/local/lib/python3.5/dist-packages/pytradfri-2.2.1-py3.5.egg/pytradfri/device.py", line 51, in has_light_control
return (ATTR_LIGHT_CONTROL in self.raw and

TypeError: argument of type 'NoneType' is not iterable

So there is one device, however not a device with light_control.
The script should catch this.

Ofcourse this is a minor bug.
Thanks for this nice module!
Rudy

**Comment by ggravlingen** [comment]
Can you please paste the code you're using to cal has_light_control?

**Comment by rudyvan** [comment]
i added the test with dev.raw to work around the bug.
Here is the code, apologies for not being pep8 format.
```python
		# ikea_drv.gen_obj = yield from api_factory(ikea_it.ip, ikea_it.secret) #async
		ikea_drv.gen_obj = api_factory(ikea_it.ip, ikea_it.secret) #sync
		ikea_drv.gateway = Gateway()
		ikea_drv.dev_cmd = ikea_drv.gateway.get_devices()
		#ikea_drv.dev_cmds = yield from ikea_drv.gen_obj(ikea_drv.dev_cmd) #async
		#ikea_drv.devs = yield from ikea_drv.gen_obj(*ikea_drv.dev_cmds) #async
		ikea_drv.dev_cmds = ikea_drv.gen_obj(ikea_drv.dev_cmd) #sync
		ikea_drv.devs = ikea_drv.gen_obj(*ikea_drv.dev_cmds) #sync
		ikea_drv.lights = [dev for dev in ikea_drv.devs if dev.raw is not None and dev.has_light_control]
		ikea_drv.sensors = [dev for dev in ikea_drv.devs if dev.raw is not None and not dev.has_light_control]
		ikea_drv.tsk_cmd = ikea_drv.gateway.get_smart_tasks()
		#ikea_drv.tasks = yield from ikea_drv.gen_obj(ikea_drv.tsk_cmd) #async
		ikea_drv.tasks = ikea_drv.gen_obj(ikea_drv.tsk_cmd) #sync
		ikea_drv.grp_cmd = ikea_drv.gateway.get_groups()
		#ikea_drv.grp_cmds = yield from ikea_drv.gen_obj(ikea_drv.grp_cmd) #async
		#ikea_drv.groups = yield from ikea_drv.gen_obj(*ikea_drv.grp_cmds) #async
		ikea_drv.grp_cmds = None if not ikea_drv.lights else ikea_drv.gen_obj(ikea_drv.grp_cmd) #sync
		ikea_drv.groups = [] if not ikea_drv.lights else ikea_drv.gen_obj(*ikea_drv.grp_cmds) #sync
		if type(ikea_drv.groups)!=list: ikea_drv.groups=[ikea_drv.groups] # one group

```

**Comment by ggravlingen** [comment]
PRs are always welcome if there’s functionality missing in the lib or if there’s a bug. 😊 Please make a stab at it and become a contributor.

**Comment by ggravlingen** [comment]
@rudyvan given it any thought to contribute a fix to the main library?

**Comment by rudyvan** [comment]
i think the change in device.py should be as follows:
```python3
@property
def has_light_control(self):
    return (self.raw is not None and ATTR_LIGHT_CONTROL in self.raw and
                len(self.raw.get(ATTR_LIGHT_CONTROL)) > 0)
```
alternatively the conditional could be shortened as:

```python3
return (self.raw is not None and len(self.raw.get(ATTR_LIGHT_CONTROL,"")) > 0)
```
i don't know github that well to start a branch and ask for a pull

**Comment by ggravlingen** [comment]
@rudyvan that's a pity! I didn't know much either when I started this project but there are many out there to help. In short: you fork a repo (from the github web page), create a new branch (can be done using the desktop app), switch to that branch (can also be done using the desktop app), make the changes in the device.py, test functionality, check in the code and then make a pull request based on that branch.

**Comment by lwis** [comment]
@rudyvan https://opensource.guide/how-to-contribute/#opening-a-pull-request
if you're interested. Everyone's welcome! Plus if you make 4 contributions
in during Hacktober you get a free t-shirt 👍
