### ISSUE TITLE
Move discovered tradfri-behaviour specific code from home-assistant to pytradfri

### ISSUE THREAD

**Issue by matemaciek** [ggravlingen/pytradfri#65]
Suggested specification:
- `LightControl` will receive new methods:
  - `can_set_color` - returns whether controlled light supports arbitrary color. If so, all of following should change color of light as requested: `set_hex_color`, `set_xy_color`, and `set_rgb_color`. The range of supported colors is not specified, but if some color works in one space and can be specified in other space it should also work there.
  - `can_set_kelvin` - returns whether controlled light supports color temperature. If so, `set_kelvin_color` should change color of light as requested. The range of supported tempertures is defined by methods `min_kelvin` and `max_kelvin`.
  - `min_kelvin` - explained above.
  - `max_kelvin` - explained above.
- `Light` will satisfy following speciffication:
  -  `kelvin_color`, `xy_color`, `hex_color` and `rgb_color` will return colors coresponding to actual state of the bulb, regardles of bulb type (white / white spectrum / color & white spectrum). Exception: `kelvin_color` on colors outside of white spectrum may return `None`. Boundaries of white spectrum in colored spaces are not strictly defined.

**Comment by matemaciek** [comment]
I'm currently working on described changes, so anyone with enough power can assign this issue to me.

**Comment by ggravlingen** [comment]
Great initiative! 🎉

**Comment by balloob** [comment]
I like it!

**Comment by matemaciek** [comment]
Just imagine how neat `home-assistant`'s code responsible for tradfri will get (-:

**Comment by ggravlingen** [comment]
I guess #67 is a pre-requisite for solving this issue?

**Comment by matemaciek** [comment]
#67 is a first part - whell, technically second - taking care of `Light` behaviour.

**Comment by ggravlingen** [comment]
@matemaciek are we ready to close this issue now?

**Comment by matemaciek** [comment]
@ggravlingen I think we need to sort up setters also - since some of them are doing conversions, and some are just setting API parameters. Especially `set_hex_color` is only working for some hex values, although we now how to set them for more values.

**Comment by ggravlingen** [comment]
Ah, I see, that makes sense. Would you be interested in also adding these setters to the lib since you know the structure behind the getters?

**Comment by matemaciek** [comment]
Yes, I'm planning to do so (-: What do you think about suffixing "magic" setters with `_inferred`, as we did in getters?

**Comment by matemaciek** [comment]
BTW I think that setting hex/rgb should also set brightness, not only x and y. @r41d , what do you think?

**Comment by ggravlingen** [comment]
@matemaciek yes on ```_inferred```.

**Comment by ggravlingen** [comment]
We've taken a new path on color handling. I've done some reading up on the issue and it showed to be quite complicated. Therefore, the lib now only supports what the gateway does and so any conversion has to be done separately as there are more clever people out there into the maths of color conversion. The colormath lib seemed quite handy so I made a simple example based on that. That said, thanks for quickly adding support for colors to the lib @r41d and @matemaciek, your work has helped a lot of users get Tradfri whitespace and color bulbs into their echosystems!
