### ISSUE TITLE
script/dev_docker broken on OS X

### ISSUE THREAD

**Issue by balloob** [ggravlingen/pytradfri#7]
Script fails with the following error:

```
script/dev_docker: line 16: syntax error near unexpected token `;;'
```

**Comment by ggravlingen** [comment]
Unfortunately, I don't have access to a Mac right now so I can't unit test. My research has indicated that this may be related to character encoding so I've reinserted every line break and space again. For some people, that appeared to help

**Comment by balloob** [comment]
Didn't help. It doesn't like the syntax. I tried with both `bash` and `sh`. It works fine executing it in `zsh`.

**Comment by tomgidden** [comment]
@ggravlingen I'm fairly sure this isn't a character encoding issue. I think it's probably syntax, with some shells borking on the close parenthesis of the case statements within the `$(` construct. It's unnecessarily complex.

It seems to work better if:
```
DOCKERFILE=$(case "$MACHINE" in
  armv7l) echo "DockerfileRPI" ;;
  *)      echo "Dockerfile" ;;
esac)
```
is replaced by the simpler:
```
case "$MACHINE" in
  armv7l) DOCKERFILE="DockerfileRPI" ;;
  *)      DOCKERFILE="Dockerfile" ;;
esac
```
