### ISSUE TITLE
Usage broken after v2.2

### ISSUE THREAD

**Issue by badblocks** [ggravlingen/pytradfri#72]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
stand-alone

### Version of pytradfri
\>2.2

### Expected behaviour
working like \<=2.2

### Actual behaviour
using \>3.0 
```
root@rpi-srv3:~# python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytradfri.api.libcoap_api import api_factory
>>> api = api_factory("192.168.21.26", "<key>")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 131, in api_factory
      request(Command('get', ['status']))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 78, in request
      return _execute(api_commands[0])
TypeError: 'Command' object does not support indexing
```

I know some things have changed but examples in code are not working anymore. Please clarify.

**Comment by ggravlingen** [comment]
Thanks for the feedback! I'll try to replicate the error. You are not running through docker but rather directly from shell?

**Comment by badblocks** [comment]
Yes

**Comment by rudyvan** [comment]
i had the same issue and i just updated in the pytradfri/pytradfri/api/libcoap_api.py:
```python3
return _execute(api_commands)
```
.. and did again python3 setup.py install
i 'll do a fork

**Comment by tactmaster** [comment]
I have got the same error using version (however version 2.2.3 works for me)
(I am using a clean venv on an RPi2 stetch using command python3 -i -m pytradfri 10.0.0.118 xxxx-key--xxx)

**Comment by ggravlingen** [comment]
@rudyvan you deleted the PR? May I ask you to resubmit it so that we can fix main?

**Comment by rudyvan** [comment]
Dear Patrik, i am traveling now and i will be off the air for 2 weeks.
in pytradfri/pytradfri/api/libcoap_api.py, line 78, replace:
```python3
return _execute(api_commands[0])
```
with 
```python3
return _execute(api_commands)
```
and it should work.

**Comment by ggravlingen** [comment]
@rudyvan OK, will do. Thanks for finding a fix for the issue!

**Comment by ggravlingen** [comment]
@badblocks can you please try by fetching pytradfri 3.0.3, where I've added the fix suggested by @rudyvan

**Comment by badblocks** [comment]
Yes, I did a quick test with 3.03 and it's working ok again.

**Comment by ggravlingen** [comment]
Great news!
