### ISSUE TITLE
Script for tinyDTLS missing

### ISSUE THREAD

**Issue by UserXYZ** [ggravlingen/pytradfri#74]
I'm trying to replace libcoap's coap-client in my python code due to libcoap's strange behaviour/implementation regarding resource observation, and I found your code which pretty much looks like a good replacement for the base of my whole Tradfri monitoring/control system.
But, since we need DTLS to communicate with the Tradfri gateway, we need to also build aiocoap with tinyDTLS, and your instructions for that point to a script that is non-existant...https://github.com/ggravlingen/pytradfri/blob/master/script/install-aiocoap.sh

Can you recreate it or, if it is not needed anymore, update the installation/compilation docs and README.md to give the valid and current instructions for preparing aiocoap for the usage with your code?

Thanks.

**Comment by ggravlingen** [comment]
This was the content of the file:
```
-#!/bin/sh		
 -cd ../..		
 -git clone https://github.com/chrysn/aiocoap		
 -cd aiocoap		
 -git reset --hard 3286f48f0b949901c8b5c04c0719dc54ab63d431		
 -python3 -m pip install --upgrade pip setuptools		
 -python3 -m pip install .
```

**Comment by ggravlingen** [comment]
In case you don't know, Pytradfri is used in the home automation platform [Home Assistant](https://home-assistant.io/components/tradfri/) and in there, the lib is installed using the following requirements. Maybe this will be of use when you install aiocoap?
```
REQUIREMENTS = ['pytradfri==3.0.2',
                'DTLSSocket==0.1.3',
                'https://github.com/chrysn/aiocoap/archive/'
                '3286f48f0b949901c8b5c04c0719dc54ab63d431.zip'
                '#aiocoap==0.3']
```

**Comment by ggravlingen** [comment]
I've put the script back where it used to be.
