### ISSUE TITLE
Is running on Windows possible?

### ISSUE THREAD

**Issue by JohnEdwa** [ggravlingen/pytradfri#97]
I tried to have a go by installing Python 3.6.3, running 'pip install pytradfri' and then following 'install-aiocoap.sh', and trying to run pytradfri I'm met with:
```
C:\Users\JohnEdwa>python -i -m pytradfri 192.168.10.55 INHqt7BjpXGsku4d
Traceback (most recent call last):
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\__main__.py", line 7, in <module>
    from .api.libcoap_api import api_factory
ImportError: cannot import name 'api_factory'
```

If I've understood correctly, I'd still need either libcoap or tinydtls, so the answer to my question would be no?

**Comment by ggravlingen** [comment]
@JohnEdwa are the exemples working?

**Comment by lwis** [comment]
We should re-delete install-aiocoap.sh. 

`pip install -r requirements.txt` should do.

**Comment by ggravlingen** [comment]
@lwis you mean in the repo?

**Comment by lwis** [comment]
Yup.

**Comment by ggravlingen** [comment]
I'll fix later and remove reference in Readme @lwis

**Comment by JohnEdwa** [comment]
@ggravlingen They don't.
Starting from scratch (with only 'pip install pytradfri' and copying the examples as they don't come with the lib), these are the how far I get:

**example_async.py**
* python example_async.py 192.168.10.55 INHqt7BjpXGsku4d
ModuleNotFoundError: No module named 'aiocoap'
* pip install aiocoap
Successfully installed aiocoap-0.3
* python example_async.py <blah> <blah>
ImportError: cannot import name 'tinydtls'
* pip install DTLSsocket
ModuleNotFoundError: No module named 'Cython' 
* pip install Cython
Successfully installed cython-0.27.2
* pip install DTLSsocket
```
Installing collected packages: DTLSsocket
  Running setup.py install for DTLSsocket ... error
    Complete output from command c:\users\johnedwa\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JohnEdwa\\AppData\\Local\\Temp\\pip-build-e
pld84fl\\DTLSsocket\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JohnEdwa\AppDa
ta\Local\Temp\pip-cc65d2aj-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\DTLSSocket
    copying DTLSSocket\__init__.py -> build\lib.win-amd64-3.6\DTLSSocket
    copying DTLSSocket\DTLSSocket.py -> build\lib.win-amd64-3.6\DTLSSocket
    running build_ext
    Running: autoconf
    error: [WinError 2] The system cannot find the file specified
```
I get the same if I try the 'pip install -r requirements.txt' as well.

**example_sync.py**
* python example_sync.py 192.168.10.55 INHqt7BjpXGsku4d
```
Traceback (most recent call last):
  File "example_sync.py", line 107, in <module>
    run()
  File "example_sync.py", line 49, in run
    psk = api_factory.generate_psk(sys.argv[2])
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\api\libcoap_api.py", line 156, in generate_psk
    self._psk = self.request(command)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\api\libcoap_api.py", line 93, in request
    return self._execute(api_commands)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\api\libcoap_api.py", line 80, in _execute
    return_value = subprocess.check_output(command, **kwargs)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by lwis** [comment]
@JohnEdwa it looks like you're missing autoconf;

```
Running: autoconf
    error: [WinError 2] The system cannot find the file specified
```

Moreover, please don't install aiocoap directly from pypi. The version we reference is unreleased; https://github.com/ggravlingen/pytradfri/blob/master/requirements.txt#L1

**Comment by JohnEdwa** [comment]
@iwis Right, I got the pypi version of aiocoap because the requirements.txt doesn't install it if DTLSsocket installation fails, so I didn't realize it was supposed to install that as well. Still, doesn't fix the issue as I'm still missing DTLSsocket.
It did change the error though:
```
Traceback (most recent call last):
  File "example_async.py", line 115, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "example_async.py", line 45, in run
    psk = yield from api_factory.generate_psk(sys.argv[2])
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\api\aiocoap_api.py", line 193, in generate_psk
    self._psk = yield from self.request(command)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\api\aiocoap_api.py", line 149, in request
    result = yield from self._execute(api_commands)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\api\aiocoap_api.py", line 139, in _execute
    _, res = yield from self._get_response(msg)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\pytradfri\api\aiocoap_api.py", line 92, in _get_response
    r = yield from pr.response
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocoap\protocol.py", line 814, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocoap\protocol.py", line 863, in _run
    blockresponse = yield from blockrequest.response
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocoap\protocol.py", line 693, in _init_phase2
    yield from self.protocol.fill_remote(self.app_request)
  File "C:\Users\JohnEdwa\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocoap\protocol.py", line 426, in fill_remote
    raise RuntimeError("No transport could route message")
RuntimeError: No transport could route message
```

Now, pip didn't find anything for autoconf nor autotools, and 'pip install autoconfig' didn't fix anything. Installing the [GnuWin32 autoconf](http://gnuwin32.sourceforge.net/packages/autoconf.htm) didn't seem to do anything either, and neither did trying with Cygwin or MinGW/MSYS, so I'm out of ideas on how to get that sorted out.

**Comment by lwis** [comment]
@JohnEdwa Sorry, I can't help you with Windows installation issues wrt Cython.

**Comment by ggravlingen** [comment]
@JohnEdwa have you looked into running a virtual machine running Linux on your Windows machine? Virtualbox isn't that bad (https://www.virtualbox.org/) - I used to run it in the past when developing the fist versions of pytradfri.

**Comment by morberg** [comment]
Isn't Docker available for Windows as well? That might be even easier than setting up a VM.

**Comment by JohnEdwa** [comment]
Both sound like viable workarounds for the development. While I don't want to fire up a VM every time I want to turn on my lights, pyInstaller might make the end result run on Windows as well. Maybe.
Having a go at it will be a lot less work than trying to make libcoap and DTLSSocket work on Windows, at least.

**Comment by ggravlingen** [comment]
Quickly looked at pyinstaller - does it work with pytradfri?

**Comment by JohnEdwa** [comment]
@ggravlingen It does. Both examples work even with Python3 completely removed.
Doesn't resolve this issue though as it can't create Windows executables on Linux - you need to run it on a Windows machine, and we are back to square one. However, if someone was able to do it, pyinstaller could most likely be used to create a standalone commandline-wrapper-executable-thingamabob of pytradfri for Windows.

But I'd say pytradfri is not Windows compatible right now, not until someone figures out how to get DTLSSocket and/or libcoap to compile on Windows either by modifying the libraries/install scripts, or figuring out a way to get the necessary tools to work.

**Comment by ggravlingen** [comment]
@JohnEdwa I'm sure someone will come around and resolve the issue in due time. Until then, I'm closing the issue as I'm not sure we can reach further for the moment.

**Comment by Wizek** [comment]
Has anyone tried via WSL (Windows Subsystem for Linux)?

**Comment by hioctane61** [comment]
This is an old thread but just to give my experience with pytradfri and windows 10.
The libcoap_api class builds a command that needs to be executed as a python subprocess. The "base_command" looks something like:
coap-client - u tradfri -k PSK -v 0 -m ....
There's no coap-client implementation for windows. 
"The system cannot find the file specified" is returned.
Best to run this (cool) api in linux which i plan to do with virtualbox (handier than dual boot).

**Comment by szikra** [comment]
Hi, 
I have the same issue: DTLSSocket failing to install on Windows... in 2019... and this was one of the top Google results.

So i guess the answer is NO. (Is running on Windows possible?) (I mean running natively, not on Linux in a VM)

I'm not sure if closing the issue, ignoring it and hoping 'someone will come around and resolve the issue' is working out :(

I'm gonna spend some more time trying to figure out a fix for windows before moving everything to a raspberry pi... or just giving up

**Comment by boekabart** [comment]
> So i guess the answer is NO. (Is running on Windows possible?) (I mean running natively, not on Linux in a VM)

Yes it is, by using WSL (Windows Subsystem for Linux). Windows 10 / 2016 / 2019.
Either using add/remove windows features (WSL), then MS Store (Ubuntu 18), or powershell:

`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
(reboot)
`curl.exe -L -o ubuntu-1804.zip https://aka.ms/wsl-ubuntu-1804`
`Extract-Package ubuntu-1804.zip c:\WSL\Ubuntu1804`
`rm ubuntu-1804.zip`
for some extra speed:
`Set-MpPreference -ExclusionPath "C:\WSL"`
`cd c:\WSL\Ubuntu1804`
`start ubuntu1804.exe`
(first time install takes a bit)
Then you MUST update apt-get
`sudo apt update`
and optionally, 
`sudo apt upgrade`
before you can get python up to speed and install autoconf.
`sudo apt install python3-pip autoconf`

**Comment by szikra** [comment]
@boekabart Thanks, this might be useful... to someone.

I guess we have a different understanding what natively means. You might be technically right, but it's still running on a Linux subsystem and not Windows kernel directly... (I don't like Cygwin solutions either but they are a step closer.) The "ONCE IN UBUNTU" line suggest that we are not really in Windows anymore even if we are still running Windows. 
Anyway as far as I can tell this would install a separate python as well which is not what I want.

I use Windows 7 so your solution doesn't work for me anyway.

I didn't have time to rewrite it to conditionally compile with winsock2, so I just installed it on a raspberry pi, it's running fine...

**Comment by boekabart** [comment]
> You might be technically right, but it's still running on a Linux subsystem and not Windows kernel directly... (I don't like Cygwin solutions either but they are a step closer.)

I think I have to disagree with your claim that Cygwin is a step CLOSER to native - WSL is definitely closer to native than Cygwin - and it IS on the windows kernel directly - WSL is "just" an implementation of the linux kernel API that translates directly in the the windows kernel APIs.

**Comment by boekabart** [comment]
Having said that - I also ended up being most happy with running Hass.io on a PI3 ;)
