### ISSUE TITLE
Light ID

### ISSUE THREAD

**Issue by xt16johnny** [ggravlingen/pytradfri#99]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Standalone

### Version of pytradfri
Latest

### Expected behaviour
More of a request for assistance than issue - is it possible to send a device ID to the program instead of an array [0]/[1]/[2]?
On restart of the gateway the order tends to change, resulting in lights being assigned a different number. 
My planned usage is 'python3 pytradfri-program.py 65545 on' where 1 represents the change_state. 
I understand usage of sys.argv. 

Thank you

**Comment by ggravlingen** [comment]
@xt16johnny I'm afraid not in the way the library works today. Wouldn't it be possible to create such a bridge in your pytradfri-program.py?
